### ISSUE TITLE
NKAI ignores shipyards 

### ISSUE THREAD

**Issue by val-gaav** [vcmi/vcmi#2018] opened 2023-04-17 21:24 UTC
**Describe the bug**
NKAI on island like maps explores only main island and does not capture shipyard and venture into the sea.

**Game logs**
Attached a save game and logs. Resourceful AI is on and heroes are limited to 2 per player, however tested it without this mod and AI behaves the same, just buys more heroes. 

**To Reproduce**
Play a random generated map with islands settings and no underground tested with 2player setting (one human one AI)

**Expected behavior**
AI should at some point try conquer other island and venture into the sea

**Actual behavior**

AI seems to be stuck on island and ignores the shipyard building

**Did it work earlier?**

Last time I played around vcmi 1.0 AI was capturing shipyards and exploring water more or less fine. 

**Screenshots**

**Version**
 - OS: Linux 
[Archiwum.zip](https://github.com/vcmi/vcmi/files/11255954/Archiwum.zip)

 - Version: 1.2

**Comment by IvanSavenko** [comment] 2023-04-17 21:28
@nullkiller regression from #1780 ?
AI ignores shipyards of a different (e.g. neutral) players?
Bug with stealing resources mentioned in that PR has been fixed by the way

**Comment by nullkiller** [comment] 2023-04-18 05:27
Allied shipyard is ignored. If the bug was fixed I will test it. Also ensure that shipyard is usable. Because it is not the first time I see unusable shipyards on maps.

**Comment by nullkiller** [comment] 2023-04-18 05:34
Shipyard is valid. AI tries to hire a hero. Will investigate it.

**Closed** 2023-04-25 18:42 UTC
Labels: bug, nullkillerai
