### ISSUE TITLE
Perform some clientside reaction when host leaves 1 vs 1 multiplayer game (happens at least during host turn)

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#2420] opened 2023-07-26 19:40 UTC
As in title - currently the "guest player" is stuck until he figures out on his own that host has left and server has closed.

**Comment by IvanSavenko** [comment] 2023-08-08 22:16
Duplicate of https://github.com/vcmi/vcmi/issues/2061

**Closed by IvanSavenko** 2023-08-08 22:16 UTC
Labels: enhancement, client, multiplayer
