### ISSUE TITLE
Game crashes when pressing "enter" in a creature bank

### ISSUE THREAD

**Issue by wnukos** [vcmi/vcmi#4077] opened 2024-06-03 08:51 UTC
**Describe the bug**

During a fight in a creature bank the game crashes when "enter" key is pressed.

**Game logs**
[VCMI_client.exe_crashinfo.dmp](https://github.com/user-attachments/files/15531259/VCMI_client.exe_crashinfo.dmp)

[VCMI_Client_log.zip](https://github.com/user-attachments/files/15531260/VCMI_Client_log.zip)

**To Reproduce**
1. Generate a random map, for example Jebus Cross
2. Start a fight in a creature bank (crypt, griffin conservatory etc.)
3. Press enter

**Comment by IvanSavenko** [comment] 2024-06-03 08:53
Technically - duplicate of #4067

Fixed in beta branch, will be released as part of 1.5.3

**Closed by IvanSavenko** 2024-06-03 08:53 UTC
Labels: bug
