### ISSUE TITLE
When heroes are meeting in a town and one of them has a "scholar" skill, they won't exchange their spells

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2901] opened 2023-09-22 15:08 UTC
**Describe the bug**
If you will summon a heroes meeting screen with a button on a townscreen, heroes won't exchange their spells despite having "scholar" skill

**Version**
 - OS: [Windows 10]
 - Version: [VCMI 1.3.2]

**Comment by kodobi** [comment] 2023-09-28 10:51
Duplicate of #2878

**Closed** 2023-09-28 11:23 UTC
Labels: bug
