### ISSUE TITLE
Crash when playing without base game music files with Tides of War mod active

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#1372] opened 2023-01-05 14:37 UTC
**Describe the bug**
Game crashes on adventure map when playing without music files, while Tides of War mod is active. I suspect presence of extra AI turn mp3 files in Tides of War mod may be the cause

**Game logs**
[Logs](https://www.mediafire.com/file/flqonmyxies4vv4/musiccrash.zip/file)

**To Reproduce**
1. Delete base game music files
2. Activate Tides of War in launcher
3. Pick whatever map where you start with 1 town and hero (Arrogance worked for me as example)
4. keep skipping turns - after few turns game crashes

**Expected behavior**
Game doesn't crash and new turn starts correctly

**Actual behavior**
Crash... surprising?

**Did it work earlier?**
I don't know

**Version**
 - OS: Kubuntu 22.04
 - Version: current develop branch

**Additional context**
Relevant lines from command line on crash occurrence:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Resource with name MUSIC/DIRT and type MUSIC wasn't found.

Stack trace leads to CMusicHandler.cpp line 525 - inside void CMusicHandler::musicFinishedCallback()

**Comment by SergeyG22** [comment] 2023-01-11 18:10
I don't see anything strange. The error is caused by the missing resource 'DIRT.MP3'. It is in the MP3 folder.
If you put it there, the error will disappear, but after a few moves another one will appear. Also related to the missing resource.
![image3](https://user-images.githubusercontent.com/46799640/211884741-7eee4026-5271-4746-b554-797844074ee3.jpg)

**Comment by dydzio0614** [comment] 2023-01-11 18:23
The problem is VCMI is supported to work without music files as far as I know

**Comment by kambala-decapitator** [comment] 2023-01-11 19:41
haven't tested Tides of War yet, but "plain" SoD works perfectly without mp3 folder on macOS and iOS

**Comment by IvanSavenko** [comment] 2023-04-11 12:20
Fixed in 1.2

**Closed by IvanSavenko** 2023-04-11 12:20 UTC
Labels: bug, client
