### ISSUE TITLE
Crash after attacking garrison in campaign

### ISSUE THREAD

**Issue by ViaFerrata** [vcmi/vcmi#2267] opened 2023-06-29 12:40 UTC
**Describe the bug**
In the Foolhardy Waywardness campaign, 2nd map, the game crashes after successfully attacking a garrison on the map.
The crash happens shortly after the battle and after returning to the map where the transfer of creatures to the garrison UI shows up.

I think the crash is not limited to this scenario, I got similar crashes in the Armageddon's blade campaign, though the crash could be circumvented sometimes by ignoring the garrison and using another path.  

Maybe relevant for #2259 .

**Game logs**
Please attach game logs: 
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11905689/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11905691/VCMI_Server_log.txt)
[Saves.zip](https://github.com/vcmi/vcmi/files/11905707/Saves.zip)

**To Reproduce**
1. Load savegame "C".
2. Attack garrison south of 1st hero
3. Finish battle, get crash.

**Expected behavior**
The game should not crash.

**Actual behavior**
The game crashes.

**Did it work earlier?**
Not sure.

**Version**
 - OS: Android, Galaxy Tab S8+
 - Version: Daily ARM64, 27 Jun 2023

**Comment by IvanSavenko** [comment] 2023-06-29 19:44
Might actually be related to (or even duplicate of) #1912

**Comment by ViaFerrata** [comment] 2023-06-29 20:26
Just FYI happens for both AIs.

**Comment by nullkiller** [comment] 2023-06-30 05:52
Manual attack of garrison with a crash hardly has anything to do with AI. At least adventure one. Does your save have a lot of mods?

**Comment by ViaFerrata** [comment] 2023-06-30 09:14
Nope, just german translation and vcmi extras.

**Comment by IvanSavenko** [comment] 2023-07-27 13:08
Unable to reproduce.
Will try to look up similar crashes in Google Play stats once 1.3 is out

**Comment by ViaFerrata** [comment] 2023-07-28 09:45
Mhm weird, will also try again with 1.3.

**Comment by nullkiller** [comment] 2023-08-02 07:59
NKAI ally reveal map to player. There is an option to use VCAI ally but android launcher does not support it yet.

**Comment by ViaFerrata** [comment] 2023-08-04 17:03
So I just tried again with v1.3 aaaaand.... it works! No crash. 
Weird, same settings as with the fresh daily from 27nd June.

@nullkiller 
This seems to be fixed as well? No map reveal anymore by allied turn.

**Comment by IvanSavenko** [comment] 2023-08-05 13:27
Closing then

Map reveal - kind of fixed. We now use different AI for allied players. It is weaker than our main AI, but does not needs terrain reveal to work

**Closed by IvanSavenko** 2023-08-05 13:27 UTC
Labels: bug
