### ISSUE TITLE
artifacts from the warrior's tomb simply disappear

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3206] opened 2023-11-20 10:13 UTC
The hero Sorsha took the shield from the grave, but it is not in the backpack or on the hero’s doll. He just disappeared
current develop
[Sorsha.zip](https://github.com/vcmi/vcmi/files/13412641/Sorsha.zip)

**Comment by IvanSavenko** [comment] 2023-11-20 13:14
Unable to reproduce.
- Load save using build from revision c0e54b3 (last one available right now)
- Visit nearby tomb with Sorsha
Artifact goes into inventory as expected

**Comment by Povelitelh3** [comment] 2023-11-20 15:18
Yea, right. It's very strange, because I tried repeat it, started game and could repeat this problem.
But I remember when it happened I didn't close a game, I just load save and it worked. I mean, bug happened.
Must be close I suppose.

**Comment by IvanSavenko** [comment] 2024-01-15 20:37
Closing as not reproducible

**Closed by IvanSavenko** 2024-01-15 20:37 UTC
Labels: bug
