### ISSUE TITLE
In Launcher do not hide Uninstall button for submods, just disable it

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2944] opened 2023-09-25 09:14 UTC
Enable button behaves like this. Disabled when action is not possible.
Uninstall button behaves differently (Hiding it when it cannot be clicked)

If it would behave like Enable button it will consistent and more straight forward.
Additionally the notes section about mod cannot be uninstalled separately from parent can be moved in the more obvious place: to button tooltip.

**Comment by IvanSavenko** [comment] 2024-10-15 16:29
@krs0 
Unable to reproduce?
Uninstall button is present for all installed mods. If mod can't be uninstalled, then the button is disabled but visible.

**Comment by krs0** [comment] 2024-10-16 10:10
Thanks for looking. Will recheck later today.

**Comment by krs0** [comment] 2024-10-16 21:05
I have corrected the title. It was about the Uninstall button not being showed for sub-mods.
Submods cannot be uninstalled, but this I have to learn it. When switching from a mod to a submod, this button just disappeared. I was thinking that it would be more user friendly if the button was shown for submods, but disabled and show the information that submods cannot be uninstalled independently, on a tooltip of the disabled button.

**Comment by IvanSavenko** [comment] 2024-11-26 15:15
Closing / won't fix.
Buttons for action that are not possible *at all* are hidden. For example, we also don't show "install" for already installed mods or "update" for mods without available update.

Buttons for actions that are not possible *right now* and can be allowed via player actions are visible, but disabled.

**Closed by IvanSavenko** 2024-11-26 15:15 UTC
Labels: enhancement, launcher
