### ISSUE TITLE
Server crashes after learning a skill

### ISSUE THREAD

**Issue by kuang-R** [vcmi/vcmi#2154] opened 2023-05-14 03:27 UTC
**Describe the bug**
Win the siege battle at the end of the turn. The server crashes when I click to learn skills, and the screen jumps to the start interface.

**Game logs**
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11471020/VCMI_Server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11471021/VCMI_Client_log.txt)
[server_log.txt](https://github.com/vcmi/vcmi/files/11471022/server_log.txt)

**To Reproduce**
1. load save file
2. end turn
3. win the battle
4. Select skills after leveling up

**Expected behavior**
go to next turn.

**Actual behavior**
Back to the start interface

**Did it work earlier?**
Save file format not display in 1.2.1.

**Screenshots**
<img width="801" alt="Screenshot 2023-05-14 at 11 21 43" src="https://github.com/vcmi/vcmi/assets/32992558/b293018a-ba0a-4891-bf39-4867d4da6197">
<img width="804" alt="Screenshot 2023-05-14 at 11 21 59" src="https://github.com/vcmi/vcmi/assets/32992558/8fbc0f14-8420-412c-96a2-24efb81a2f4c">
<img width="803" alt="Screenshot 2023-05-14 at 11 22 05" src="https://github.com/vcmi/vcmi/assets/32992558/e69c1722-1b4b-4a2f-ab0e-3ef51562f587">

**Version**
 - OS: [macOS ARM]
 - Version: [1.3.0 bfa6fc13f20c6f45797d3804ea67d5f5815fd151]

**Additional context**
[Savefile.zip](https://github.com/vcmi/vcmi/files/11471039/Savefile.zip)

**Comment by IvanSavenko** [comment] 2023-05-14 09:51
Might be (also) related to #2150 
Most likely we got two queries - town buildings visit & levelup query

**Comment by IvanSavenko** [comment] 2023-07-27 13:09
Unable to reproduce.
Will try to look up similar crashes in Google Play stats once 1.3 is out

**Comment by IvanSavenko** [comment] 2023-08-08 21:30
Duplicates of this bug:
- #2302
- #2444 

If my assumption is correct, then this bug is already fixed in beta / 1.3.1.
Don't see anything similar in crash statistics either.
Will try to reproduce just in case.

**Closed** 2023-08-11 08:37 UTC
Labels: bug
