### ISSUE TITLE
Every time I try to attack an "enemy" player, the game gives an error

### ISSUE THREAD

**Issue by BelgicaPT** [vcmi/vcmi#3018] opened 2023-10-07 09:07 UTC
**Describe the bug**
Every time I try to attack an "enemy" player, my account goes down.
Not to say that sometimes the save game/load game doesn't work very well

**Game logs**
I took a photo of the game but I don't understand how to put it here
![1](https://github.com/vcmi/vcmi/assets/147240931/8d0c31f6-f741-4f25-8b4d-6eaf7ee83a0a)

**Comment by Povelitelh3** [comment] 2023-10-07 09:13
Pls add VCMI_Client_log and VCMI_Server_log

**Comment by BelgicaPT** [comment] 2023-10-07 09:17
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12837272/VCMI_Server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12837273/VCMI_Client_log.txt)

**Comment by BelgicaPT** [comment] 2023-10-07 09:38
![image](https://github.com/vcmi/vcmi/assets/147240931/486779df-28f9-41ea-b3a5-8574cf29b872)

**Comment by Nordsoft91** [comment] 2023-10-08 15:59
Cannot reproduce. @BelgicaPT , could you please try following:
1. start new game instead of loading (daily builds have frequent changes, no save compatibility is guaranteed) and check
2. if still crash, try to disable different mods one by one to see which of them could be possible root cause

**Comment by IvanSavenko** [comment] 2023-11-19 20:28
Looks to be corrupted vcmi install.
Please reinstall vcmi. Some files that are part of installer are missing

**Comment by IvanSavenko** [comment] 2023-11-20 17:04
Closing. Unable to reproduce, likely - corrupted install

**Closed by IvanSavenko** 2023-11-20 17:04 UTC
Labels: bug
