### ISSUE TITLE
Crash server on AI turn

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4237] opened 2024-07-08 12:37 UTC
dump https://drive.google.com/file/d/1L4NsT0kG0RdqL-KMmf4CRYXkin0QG0Mw/view?usp=sharing
didn't reproduce from save

master-e1ee8df - msvc

**Comment by IvanSavenko** [comment] 2024-07-08 16:21
Duplicate of https://github.com/vcmi/vcmi/issues/3853

**Closed by IvanSavenko** 2024-07-08 16:21 UTC
Labels: bug
