### ISSUE TITLE
Cannot start map from msvc created artifacts of latest develop PRs

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1919] opened 2023-04-09 12:43 UTC
**Describe the bug**
For latest develop PRs when starting the map I get the following error:
![image](https://user-images.githubusercontent.com/15194321/230773069-55ec1941-dbdf-49a7-a489-b74d46548e28.png)

.dll is where it should be.

With mingw artifact it works.

Sidenote:
I have `tbb12_debug.dll` in installation dir!

**Version**
 - OS: Windows
 - Version: develop

**Comment by Alexander-Wilms** [comment] 2023-09-30 00:07
Is this a duplicate of https://github.com/vcmi/vcmi/issues/2029 ?

**Comment by krs0** [comment] 2023-09-30 07:49
most likely... closing this one then

**Closed** 2023-09-30 07:49 UTC
Labels: bug, buildpkg, Windows
