### ISSUE TITLE
Hero cannot transit over this tile

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#2948] opened 2023-09-25 13:14 UTC
**Describe the bug**
Very often this error pops up in development.

**To Reproduce**
Load save and press end turn

 - OS: [e.g. Windows 10]
 - Version: [VCMI 1.4.0.a36450e2d169251260f5b92a84e2e33ca653dd30]

[server_log.txt](https://github.com/vcmi/vcmi/files/12715485/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12715486/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12715487/VCMI_Server_log.txt)
![изображение](https://github.com/vcmi/vcmi/assets/36762538/358a5bfb-3148-43bd-9b29-29cccabca6f7)
[move.zip](https://github.com/vcmi/vcmi/files/12715491/move.zip)

**Comment by IvanSavenko** [comment] 2023-09-26 12:49
Duplicate of #2881

**Closed by IvanSavenko** 2023-09-26 12:49 UTC
Labels: bug
