### ISSUE TITLE
crash after a battle when you accept losses

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3016] opened 2023-10-07 04:33 UTC
The AI attacked me in the city and won. The moment I clicked OK, accepting the losses, the game just crashed.

Guys, I have a lot of mods here, I don’t know which ones need to be disabled to prevent this from happening. Or maybe it's not them at all?

[server_log.txt](https://github.com/vcmi/vcmi/files/12836779/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12836780/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12836781/VCMI_Server_log.txt)
[save.zip](https://github.com/vcmi/vcmi/files/12836783/save.zip)
![изображение](https://github.com/vcmi/vcmi/assets/36762538/3bd04f3f-9d70-493d-8ad2-4c7ed0291a35)

VCMI 1.4.0.ebe155fa95af9fb27c4ebab0e5e5ffd88d5feabb
win 10, msvc

**Comment by nullkiller** [comment] 2023-10-07 13:34
Unmovable artifact problem. Might be a duplicate of #1912

**Comment by IvanSavenko** [comment] 2023-11-19 20:38
Closing as duplicate

**Closed by IvanSavenko** 2023-11-19 20:38 UTC
Labels: bug
