### ISSUE TITLE
Sound is cracking on Linux with 1.0 build

### ISSUE THREAD

**Issue by xcom169** [vcmi/vcmi#1074] opened 2022-10-17 11:17 UTC
Hello All,

I'm using Arch Linux with Pipewire. The sound is cracking sometimes:

https://user-images.githubusercontent.com/17802090/196163791-e3852d39-c759-4cd3-bafd-b40cbbc5078d.mp4

Do you have also this issue?

Thanks!

**Comment by misiokles** [comment] 2022-10-17 16:10
In Windows version sometimes it happens too. For now, try to experiment with ambientSounds.json
For example you can change `"allocateChannels" : 16, `for higher values.

**Comment by nullkiller** [comment] 2022-10-23 13:52
Sound might have issues when CPU usage is very high. Have you noticed if this happens during AI turn or something else?

**Comment by kambala-decapitator** [comment] 2022-10-23 14:05
observed this on Debian with Alsa as well (during my turn)

**Comment by nullkiller** [comment] 2022-10-24 05:33
So does not look like CPU-bound issue.

**Comment by kambala-decapitator** [comment] 2022-11-10 09:07
however on Mint 21 with Pulse Audio I don't observe this, using all libs from apt

**Comment by xcom169** [comment] 2022-11-10 09:16
Do you use low latency kernel, or some low latency audio setting?

**Comment by kambala-decapitator** [comment] 2022-11-10 09:18
> Do you use low latency kernel, or some low latency audio setting?

no idea, sorry. How to check that?

I have simply installed fresh Mint 21 Xfce on an old MBP.

**Comment by xcom169** [comment] 2022-12-01 14:32
Hello All. 
Now the sound is beeping not cracking at my side.

**Comment by xcom169** [comment] 2022-12-02 13:05
Hello All,
Anybody has a new daily version of the SDL2 mixer . so?
I would try it with my VCMI build.

**Comment by IvanSavenko** [comment] 2022-12-02 13:30
I don't have one, but apparently there was release of libsdl 2.26.1 just yesterday which contains fix for this bug.
So I guess you should get an update soon since this is Arch Linux we're talking about.

Oh, and my bad - bug is not in SDL_Mixer but in base SDL library.

**Comment by xcom169** [comment] 2022-12-02 15:00
https://user-images.githubusercontent.com/17802090/205322054-a5d95d1d-5162-4e34-9fcc-aa6b4f11a76a.mp4

**Comment by IvanSavenko** [comment] 2022-12-08 20:14
@xcom169 
Hi. From what I understand, SDL got update on Arch Linux: https://archlinux.org/packages/extra/x86_64/sdl2/
Can you check that you have sdl2 on version 2.26.1-1 and recheck this bug?

**Comment by xcom169** [comment] 2022-12-09 11:46
@IvanSavenko  It is really nice now.  I don't hear any beeping, cracking.

**Comment by IvanSavenko** [comment] 2022-12-09 12:11
Closing as upstream bug.

Caused by bug in libsdl2, versions 2.23.0 - 2.26.0
Solution is to either upgrade to 2.26.1 or downgrade to 2.22.0

Known affected Linux distributions are:
- Debian 12 (bookworm)
- Ubuntu 22.10 (kinetic)

**Closed by IvanSavenko** 2022-12-09 12:11 UTC
Labels: bug
