### ISSUE TITLE
With skip intro option ON summoned creatures lack def animation

### ISSUE THREAD

**Issue by val-gaav** [vcmi/vcmi#2521] opened 2023-08-08 07:52 UTC
**Describe the bug**
If in battle option we select skip intro option (this skips the intro battle music) units that are summoned on combat start end up without animations. They look invisible as on the attached screenshot.

**To Reproduce**
Install courtyard mod then build town level 6 creature Mandrakes and buy them. Enter a combat with skip intro option. Mandrakes summon creatures called strangle vines on combat start and they are without animations. 

If skip intro option is not enabled creatures animation will generate properly. 

**Version**
Linux Ubuntu,  version from ppa 1.3.0

[vcmi.zip](https://github.com/vcmi/vcmi/files/12288713/vcmi.zip)
![Screenshot_20230808_092230](https://github.com/vcmi/vcmi/assets/104362626/524ff71b-e919-497d-a388-b63eda3ab96a)

**Comment by IvanSavenko** [comment] 2023-09-06 08:20
Closing as duplicate of #2477

**Closed by IvanSavenko** 2023-09-06 08:20 UTC
Labels: bug, modding, visibility
