### ISSUE TITLE
[1.5.7] game crashed when enter next scenario in campaign

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4635] opened 2024-09-21 14:10 UTC
**Describe the bug**
This Save file will lead a crash when goes into next scenario.

[crash_save.zip](https://github.com/user-attachments/files/17084276/crash_save.zip)

dmp file: 
[VCMI_client.exe_crashinfo.zip](https://github.com/user-attachments/files/17084300/VCMI_client.exe_crashinfo.zip)

Mods:
https://drive.google.com/file/d/1BQRLJFqQ_Qs9Kwg_hpGVNfRrS4ygKHRF/view?usp=sharing

**Game logs**
log file: 
[VCMI_Client_log.txt](https://github.com/user-attachments/files/17084322/VCMI_Client_log.txt)

**To Reproduce**
1. enable all mods
2. load game save in campaign
3. win the last battle to next scenario.
4. pick bonus  ans start next scenario
5.  game crash 

**Expected behavior**
game  not crash 

**Actual behavior**
game crash

**Did it work earlier?**
since 1.5.3  to 1.5.7

**Screenshots**
no

**Version**
 - OS: All
 - Version: 1,5,7
 - 
**Additional context**
no

**Comment by IvanSavenko** [comment] 2024-09-22 19:06
Reproduced, thanks for the save.
Knew about this crash for quite some time but couldn't find steps to reproduce it.

**Comment by dydzio0614** [comment] 2024-09-22 19:18
@IvanSavenko maybe fix in beta and release 1.5.8?

**Comment by IvanSavenko** [comment] 2024-09-22 19:26
This crash is quite rare, but was rather persisting - I think I saw it around 1.5.0, and couldn't figure it out all that time.

In total right now we have ~5 different crashes that I can't figure out:
- crash due to corrupted RMG map - player present with 0 towns/heroes
- crash on battle end due to hero that was in battle not present on map for whatever reason
- crash on closing game (during AI turn?)
- crash on closing map setup screen (no ideas...)
- crash on app startup due to some weirdness with permissions to our internal directory

Campaign crash is not even in top 5 here... So even if we were to fix it it won't help much with stability.

**Closed** 2024-09-23 15:01 UTC
Labels: bug
