### ISSUE TITLE
lag in video intro 

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4160] opened 2024-06-18 12:42 UTC
https://youtube.com/shorts/4iWFJ5Ep6_Q

1.5.2, Android

**Comment by IvanSavenko** [comment] 2024-06-18 13:19
- Do you have the same issue when running vcmi on PC using same data files?
- Can you extract both H3Intro.smk and H3Intro.bik from Video.vid and upload them on Google Drive or similar?

**Comment by Povelitelh3** [comment] 2024-06-18 15:53
@IvanSavenko 
on PC I have crash https://drive.google.com/file/d/1KZy70AP0Z8dSLRZYLdJZOOMq8ziQjMqI/view?usp=drive_link 1.5.2 alternate
video.vid https://drive.google.com/file/d/1IYjxxCa8h4q1LF2LjSkmUeF3xdCXooOg/view?usp=drive_link

**Comment by IvanSavenko** [comment] 2024-06-18 16:04
May be already fixed in 1.6. But too risky to backport to 1.5.x
Will recheck after 1.5.3 release.

**Comment by Povelitelh3** [comment] 2024-06-18 16:50
> May be already fixed in 1.6. But too risky to backport to 1.5.x Will recheck after 1.5.3 release.

in beta 1.5.3.af5572db1555daa5e5240e8e23ee6628e084a1e0 I have speed lag
develop [3a602bd](https://github.com/vcmi/vcmi/commit/3a602bd3d40afe2b57097468667c20cd6f9cad05) no speed lag
but no sounds in this scene

**Comment by Povelitelh3** [comment] 2024-06-19 06:57
*need to be clarified. The first case with a crash dump where I had an accident, the data was from the English version. The second case was with a Russian. There is no longer a crash dump, but there are lags as in the video.

**Comment by Alexander-Wilms** [comment] 2024-06-20 17:05
I can reproduce this lag with the Android ARM64 build of c8aeee764bbb37750bb4ed45fa3c83eef3039dce

1.5.2 works fine.

**Comment by Povelitelh3** [comment] 2024-06-22 07:27
1.5.3, Android, russian lokalization
https://youtu.be/zOVXbI3DZ0A

**Comment by Povelitelh3** [comment] 2024-06-28 17:44
1.5.3, alternate, win10  https://youtu.be/lvgS1tEufeg and so on until the end

**Comment by IvanSavenko** [comment] 2024-07-16 12:44
Seems to be fixed for me in 1.6.

Not something I am willing to backport to 1.5

> For me it depends on the interface scaling
> Does an interface scaling of 50% create a texture that's 4x larger?

Yes, everything is rendered at double resolution and then downscaled by SDL to window size.
Might take a look at it later, but 50% resolution scale is not exactly playable especially on low-end devices. It was mostly added to allow playing on devices with screen smaller than 800x600 - to allow some downscaling. Not for FullHD and larger displays.

**Comment by IvanSavenko** [comment] 2024-07-16 12:46
Interesting minor glitch - due to way we play video, audio is actually controller by sound effects volume, and not by music volume.

**Closed** 2024-07-18 18:18 UTC
Labels: bug
