### ISSUE TITLE
Not able to play campaign with mods installed on android

### ISSUE THREAD

**Issue by Tooandorisu** [vcmi/vcmi#3394] opened 2023-12-25 18:48 UTC
**Describe the bug**
Not able to play campaign with mods installed.
![Screenshot_20231224_214333_VCMI](https://github.com/vcmi/vcmi/assets/11391798/450f1794-d0f2-4f37-947b-4e3ef9f84cd2)

** logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
Download all towns/expansion mod, play a while, loose, load game, error pops up.

**Expected behavbehaviour 
Be able to load  save game

**Actual behavior**
Not being able to load save game

**Did it work earlier?**
No idea

**Screenshots**
Added 

**Version**
 - OS: Android 
 - Version: 1.4.2

**Additional context**
Uploading server and client txt when I'm home

**Comment by IvanSavenko** [comment] 2024-01-06 11:57
Unable to reproduce
- Start game
- Start campaign "Long live the queen"
- play for a few turns
- end game with 'vcmilose'
- attempt to load autosaves: OK

**Comment by IvanSavenko** [comment] 2024-04-06 14:45
Closing, unreproducible

**Closed by IvanSavenko** 2024-04-06 14:45 UTC
Labels: bug
