### ISSUE TITLE
Softlock when one player get eliminated in alliance mode

### ISSUE THREAD

**Issue by ToRRent1812** [vcmi/vcmi#3444] opened 2024-01-06 12:56 UTC
**Describe the bug**
Whenever we play hotseat alliance (2 players in 1 team) against AI, and one of the players in alliance gets eliminated (lost all towns and heroes), the game shows information that player is eliminated and then it softlocks and nothing happens, You can't click on anything, game looks paused.

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/13849717/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13849718/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13849732/VCMI_Server_log.txt)

**To Reproduce**
1. Play a scenario as alliance against AI
2. Lose

**Expected behavior**
The game should move to next turn as next player is still available to play

**Actual behavior**
The game gets stuck, and shows hourglass icon as vcmi expects AI player to do something

**Did it work earlier?**
I started playing vcmi since 1.4 and it always happen

**Screenshots**
![Screenshot_20240106_134734](https://github.com/vcmi/vcmi/assets/4561094/8df2c4e0-b4f8-4f27-9cb9-cf7c1cb64199)

**Version**
 - OS: Linux - OpenSUSE Tumbleweed
 - Version: 1.42

**Comment by IvanSavenko** [comment] 2024-01-15 17:05
Unfortunately unable to reproduce this

**Comment by nullkiller** [comment] 2024-05-11 06:42
Might be something mod specific. Client log says that server crashed but server log says nothing about it so maybe it was just closed. Was not able to reproduce it in 1.5 either.

**Comment by IvanSavenko** [comment] 2024-05-28 17:16
Closing, unable to reproduce. Please reopen if this happens again

**Closed by IvanSavenko** 2024-05-28 17:16 UTC
Labels: bug, client, hotseat
