### ISSUE TITLE
Cannot pass artifacts between heroes

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#3056] opened 2023-10-14 23:46 UTC
**Describe the bug**
Severe problem in release build...

**To Reproduce**
1. Start hero dialog
2. Pass artefact to another hero

**Expected behavior**
Artifact transferred

**Actual behavior**
Server error

**Did it work earlier?**
Yes

**Screenshots**

https://github.com/vcmi/vcmi/assets/9308612/9380751a-8b1c-4714-a90b-43b67a25d0e9

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: 1.3.2
 - mod: extras, courtyard town

**Additional context**

Artifacts seems one of the most buggy functionality

**Comment by SoundSSGood** [comment] 2023-10-15 08:15
I only see issues with queries in the video. Can someone who is more familiar with queries check this out?

**Comment by nullkiller** [comment] 2023-10-29 13:08
Without savefile it looks more like an issue we are never going to fix. With savefiles we could potentially try to load save so it will force us to build older version of develop because of save compatibility. So candidate for closing as won't fix. Hope it is duplicating heroes issue and my #2847 can shed some light on it

**Comment by IvanSavenko** [comment] 2023-11-19 21:04
Closing, not reproducible, very likely duplicate of #2299

**Closed by IvanSavenko** 2023-11-19 21:04 UTC
Labels: bug, advmap
