### ISSUE TITLE
Warriors tomb second visit empty message

### ISSUE THREAD

**Issue by nullkiller** [vcmi/vcmi#909] opened 2022-09-15 07:53 UTC
There is no message when you visit warriors tomb second time with the same hero.

**Comment by kambala-decapitator** [comment] 2022-09-21 09:20
can't reproduce in the latest develop:

https://user-images.githubusercontent.com/1557784/191466721-55456330-d38c-458f-930c-ed4477b2d941.mov

should we close the issue?

**Closed** 2022-09-23 08:08 UTC
Labels: bug, advmap
