### ISSUE TITLE
movement points issue on switching the fastest unit

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1402] opened 2023-01-10 08:06 UTC
**Describe the bug**
After changing the fastest unit on a hero, game doesn't immediately see that the hero now has more movement points.

**To Reproduce**
My steps were:
1. have a hero in town garrison with Hobgoblins
2. move him to the visiting slot, close town UI
3. open town again, hire a Dragon Fly, replace Hobgoblins with Dragon Fly on the hero
4. go somewhere with the hero
5. observe that hero still have movement points (the green bar) although he can't move any more
6. switch to another hero, switch back
7. now you can use the rest of the movement points

**Expected behavior**
hero can use full points without switching to another hero

**Actual behavior**
hero can't move although still has some points, see SS

**Did it work earlier?**
no idea

**Screenshots**
![Screenshot 2023-01-10 at 10 03 46](https://user-images.githubusercontent.com/1557784/211495325-b11f9d36-5fda-4d30-85bb-adcba7880a6d.png)

**Version**
 - OS: macOS Intel
 - Version: the latest develop

**Comment by dydzio0614** [comment] 2023-01-11 19:14
Actually the bug is different - movement points boost from creatures should only apply on start of new turn

**Comment by kambala-decapitator** [comment] 2023-01-16 15:05
> Actually the bug is different - expected behavior is: movement points boost from creatures should only apply on start of new turn

Yes, I think you're right

**Comment by IvanSavenko** [comment] 2023-06-21 17:37
Unable to reproduce on current develop.

Likely fixed by bonus system refactoring.

**Closed** 2023-06-25 18:13 UTC
Labels: bug, advmap
