### ISSUE TITLE
Battle stucks dusing siege

### ISSUE THREAD

**Issue by ivanvasheka** [vcmi/vcmi#4582] opened 2024-09-12 10:27 UTC
**Describe the bug**
When AI attacks a castle and siege is underway. When all the creatures (from my side) are dead and I should lose, battle stucks...

**Game logs**
-

**To Reproduce**
Don't know exact steps, happen from time to time when playing vs AI and only when AI attacks my castle.

**Expected behavior**
When my last creature dies during siege a win should be counted for the AI.

**Actual behavior**
When AI attacks a castle and siege is underway. When all the creatures (from my side) are dead and I should lose, battle stucks...

**Did it work earlier?**
Worked fine previously

**Screenshots**

**Version**
 - OS: macOS ARM
 - Version: 1.5.7

**Additional context**

**Comment by Bonbadil** [comment] 2024-09-18 16:46
Hello,
I've encountered the same problem, on my VCMI 1.5.7 x64 on my Ubuntu LTS 24.04.
Can I help? Maybe giving savegames or logs or testing builds? My game with my son is blocked because the game always stuck on the AI turn.

**Comment by IvanSavenko** [comment] 2024-09-18 16:47
Save please.
Go to Launcher -> About -> User data directory to find where saves are

**Comment by Bonbadil** [comment] 2024-09-18 16:55
You just have to end the blue player2's turn, and the violet AI player should attack a red player1's city and easily win.

**Comment by IvanSavenko** [comment] 2024-09-19 15:44
@Bonbadil 
Fix is ready, but unfortunately at the moment we don't have daily builds for Ubuntu.
As a workarounds, you can:
a) dismiss garrison from that town (probably the easiest option)
b) play this game over network, at least for one turn
c) load this game in single-player as red player, pray that now-AI blue won't mess up your save too much, and reload game as hotseat once red player gets his turn

@ivanvasheka 
Were these freezes in a hotseat game by chance? If yes - then they should be fixed.

If not - are they reproducible from save? Can you upload game log after freeze?

**Comment by Bonbadil** [comment] 2024-09-19 17:38
@IvanSavenko Thank you very much for your quick fix and detailed workarounds!

**Comment by ivanvasheka** [comment] 2024-09-20 21:28
> @Bonbadil Fix is ready, but unfortunately at the moment we don't have daily builds for Ubuntu. As a workarounds, you can: a) dismiss garrison from that town (probably the easiest option) b) play this game over network, at least for one turn c) load this game in single-player as red player, pray that now-AI blue won't mess up your save too much, and reload game as hotseat once red player gets his turn d) you may try to enable quick combat. But not sure if this will let you avoid this bug
> 
> @ivanvasheka Were these freezes in a hotseat game by chance? If yes - then they should be fixed.
> 
> If not - are they reproducible from save? Can you upload game log after freeze?

Yep, it was a hotseat game, thanks!

**Comment by IvanSavenko** [comment] 2024-09-22 18:22
Closing then. Fixed in 1.6
Build for 1.5 with fix is available in here: https://download.vcmi.eu/branch/beta/
(but not for Linux)

**Closed by IvanSavenko** 2024-09-22 18:22 UTC
Labels: bug

**Comment by ivanvasheka** [comment] 2024-11-01 16:42
> Closing then. Fixed in 1.6 Build for 1.5 with fix is available in here: https://download.vcmi.eu/branch/beta/ (but not for Linux)

Can we please have a 1.6 rolled out soon? :)
