### ISSUE TITLE
[1.4.4]Game crashes when master genies buff another unit.

### ISSUE THREAD

**Issue by ninjatao** [vcmi/vcmi#3545] opened 2024-01-22 08:34 UTC
**Describe the bug**
With HOTA mod, game crashes when master genies buff another unit. VCMI 1.4.2 + HOTA does not have this problem.

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/14007193/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/14007194/VCMI_Server_log.txt)

**To Reproduce**
1. New Game -> Single Player -> Any Map -> Choose Tower
2. Recuite master genies and enter combat
3. Have master genies buff another unit
4. 100% Crash

**Expected behavior**
Game should not crash.

**Actual behavior**
Game crashed.

**Did it work earlier?**
1.4.2 Works fine.

**Screenshots**

**Version**
 - OS: Android
 - Version: 1.4.4 + HOTA 1.6.36

**Additional context**

**Comment by kambala-decapitator** [comment] 2024-01-22 09:08
duplicate of #3535 which has already been fixed

> If you wish - you can download build from here, it matches 1.4.4 + fix for some crashes, including yours (scroll to the bottom)
https://github.com/vcmi/vcmi/actions/runs/7596535174

**Closed by kambala-decapitator** 2024-01-22 09:08 UTC
Labels: bug
