### ISSUE TITLE
The scenario "Random map" always starts from the second time

### ISSUE THREAD

**Issue by gestern** [vcmi/vcmi#2666] opened 2023-08-24 19:32 UTC
**Describe the bug**
It is impossible to launch a random game the first time. 

**Game logs**
`VCMI_server.txt`:
```
2023-Aug-24 22:17:43.976029] INFO network - Client 1 player: Player
[2023-Aug-24 22:17:43.976080] INFO network - system says: Player (pid  cid 1) joins the game
[2023-Aug-24 22:19:02.767395] INFO network - Preparing to start new game
[2023-Aug-24 22:19:02.768211] INFO global - Gamestate created!
[2023-Aug-24 22:19:02.768264] INFO global - 	Using random seed: 1692904742
[2023-Aug-24 22:19:02.770714] INFO global - Create random map.
[2023-Aug-24 22:19:02.771385] INFO global - RMG map: 108x108, WITH underground
[2023-Aug-24 22:19:02.771426] INFO global - RMG settings: players -1, teams -1, computer players -1, computer teams -1, water -1, monsters -2
[2023-Aug-24 22:19:02.771463] INFO global - RMG template name: 8MM6
[2023-Aug-24 22:19:02.771512] INFO global - Final player config: 4 total, 0 cpu-only
[2023-Aug-24 22:19:02.975075] INFO global - Starting zone placement
[2023-Aug-24 22:19:02.975408] INFO global - Initial zone grid:
[2023-Aug-24 22:19:02.975426] INFO global -   1   7  17  13   5   3 
[2023-Aug-24 22:19:02.975437] INFO global -   9  19  --  25  21  12 
[2023-Aug-24 22:19:02.975446] INFO global -  15  --  --  --  --  23 
[2023-Aug-24 22:19:02.975455] INFO global -  22  --  --  --  --  18 
[2023-Aug-24 22:19:02.975465] INFO global -  11  24  26  --  20  10 
[2023-Aug-24 22:19:02.975474] INFO global -   4   6  14  16   8   2 
[2023-Aug-24 22:19:02.975491] ERROR global - Can't find info for player  (starting zone)
[2023-Aug-24 22:19:02.975505] ERROR global - Can't find info for player  (starting zone)
[2023-Aug-24 22:19:02.975514] ERROR global - Can't find info for player  (starting zone)
[2023-Aug-24 22:19:02.975523] ERROR global - Can't find info for player  (starting zone)
[2023-Aug-24 22:19:02.979261] INFO global - Starting zone colouring
[2023-Aug-24 22:19:03.055141] INFO global - Finished zone colouring
[2023-Aug-24 22:19:03.055196] INFO global - Zones generated successfully
[2023-Aug-24 22:19:03.055658] INFO global - Started filling zones
[2023-Aug-24 22:19:03.055846] INFO global - Zone 1 modificators initialized
[2023-Aug-24 22:19:03.056057] INFO global - Zone 2 modificators initialized
[2023-Aug-24 22:19:03.056354] INFO global - Zone 3 modificators initialized
[2023-Aug-24 22:19:03.056542] INFO global - Zone 4 modificators initialized
[2023-Aug-24 22:19:03.056767] INFO global - Zone 5 modificators initialized
[2023-Aug-24 22:19:03.056918] INFO global - Zone 6 modificators initialized
[2023-Aug-24 22:19:03.057134] INFO global - Zone 7 modificators initialized
[2023-Aug-24 22:19:03.057427] INFO global - Zone 8 modificators initialized
[2023-Aug-24 22:19:03.057643] INFO global - Zone 9 modificators initialized
[2023-Aug-24 22:19:03.057835] INFO global - Zone 10 modificators initialized
[2023-Aug-24 22:19:03.058120] INFO global - Zone 11 modificators initialized
[2023-Aug-24 22:19:03.058372] INFO global - Zone 12 modificators initialized
[2023-Aug-24 22:19:03.058567] INFO global - Zone 13 modificators initialized
[2023-Aug-24 22:19:03.058825] INFO global - Zone 14 modificators initialized
[2023-Aug-24 22:19:03.058993] INFO global - Zone 15 modificators initialized
[2023-Aug-24 22:19:03.059175] INFO global - Zone 16 modificators initialized
[2023-Aug-24 22:19:03.059272] INFO global - Zone 17 modificators initialized
[2023-Aug-24 22:19:03.059409] INFO global - Zone 18 modificators initialized
[2023-Aug-24 22:19:03.059684] INFO global - Zone 19 modificators initialized
[2023-Aug-24 22:19:03.059895] INFO global - Zone 20 modificators initialized
[2023-Aug-24 22:19:03.060147] INFO global - Zone 21 modificators initialized
[2023-Aug-24 22:19:03.060378] INFO global - Zone 22 modificators initialized
[2023-Aug-24 22:19:03.060505] INFO global - Zone 23 modificators initialized
[2023-Aug-24 22:19:03.060681] INFO global - Zone 24 modificators initialized
[2023-Aug-24 22:19:03.060964] INFO global - Zone 25 modificators initialized
[2023-Aug-24 22:19:03.061179] INFO global - Zone 26 modificators initialized
[2023-Aug-24 22:19:03.061375] INFO global - Modificator zone 1 - TownPlacer - started
[2023-Aug-24 22:19:03.061400] INFO global - Preparing playing zone
[2023-Aug-24 22:19:03.061416] INFO global - Modificator zone 3 - TownPlacer - started
[2023-Aug-24 22:19:03.061441] INFO global - Modificator zone 6 - TownPlacer - started
[2023-Aug-24 22:19:03.061469] INFO global - Modificator zone 9 - TownPlacer - started
[2023-Aug-24 22:19:03.061492] INFO global - Modificator zone 2 - TownPlacer - started
[2023-Aug-24 22:19:03.061516] INFO global - Preparing playing zone
[2023-Aug-24 22:19:03.061444] INFO global - Preparing playing zone
[2023-Aug-24 22:19:03.061624] INFO global - Preparing playing zone
[2023-Aug-24 22:19:03.061560] INFO global - Modificator zone 10 - TownPlacer - started
[2023-Aug-24 22:19:03.061562] INFO global - Modificator zone 7 - TownPlacer - started
[2023-Aug-24 22:19:03.061740] INFO global - Preparing playing zone
[2023-Aug-24 22:19:03.061764] INFO global - Modificator zone 1 - TownPlacer - done (1 ms)
[2023-Aug-24 22:19:03.061795] INFO global - Modificator zone 11 - TownPlacer - started
[2023-Aug-24 22:19:03.061566] INFO global - Modificator zone 4 - TownPlacer - started
[2023-Aug-24 22:19:03.061626] INFO global - Modificator zone 8 - TownPlacer - started
[2023-Aug-24 22:19:03.061927] INFO global - Preparing playing zone
[2023-Aug-24 22:19:03.061957] INFO global - Modificator zone 9 - TownPlacer - done (1 ms)
[2023-Aug-24 22:19:03.062027] INFO global - Modificator zone 2 - TownPlacer - done (2 ms)
[2023-Aug-24 22:19:03.062058] INFO global - Modificator zone 13 - TownPlacer - started
[2023-Aug-24 22:19:03.062087] INFO global - Preparing playing zone
[2023-Aug-24 22:19:03.062028] INFO global - Modificator zone 12 - TownPlacer - started
[2023-Aug-24 22:19:03.061948] INFO global - Modificator zone 5 - TownPlacer - started
[2023-Aug-24 22:19:03.062198] INFO global - Preparing playing zone
[2023-Aug-24 22:19:03.062219] INFO global - Modificator zone 7 - TownPlacer - done (3 ms)
[2023-Aug-24 22:19:03.062300] INFO global - Modificator zone 14 - TownPlacer - started
[2023-Aug-24 22:19:03.062337] INFO global - Modificator zone 6 - TownPlacer - done (2 ms)
[2023-Aug-24 22:19:03.062368] INFO global - Modificator zone 15 - TownPlacer - started
[2023-Aug-24 22:19:03.062389] INFO global - Modificator zone 15 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062399] INFO global - Modificator zone 16 - TownPlacer - started
[2023-Aug-24 22:19:03.062411] INFO global - Modificator zone 3 - TownPlacer - done (6 ms)
[2023-Aug-24 22:19:03.062433] INFO global - Modificator zone 17 - TownPlacer - started
[2023-Aug-24 22:19:03.062447] INFO global - Modificator zone 16 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062462] INFO global - Modificator zone 18 - TownPlacer - started
[2023-Aug-24 22:19:03.062472] INFO global - Modificator zone 4 - TownPlacer - done (4 ms)
[2023-Aug-24 22:19:03.062492] INFO global - Modificator zone 11 - TownPlacer - done (5 ms)
[2023-Aug-24 22:19:03.062505] INFO global - Modificator zone 19 - TownPlacer - started
[2023-Aug-24 22:19:03.062524] INFO global - Modificator zone 10 - TownPlacer - done (2 ms)
[2023-Aug-24 22:19:03.062543] INFO global - Modificator zone 21 - TownPlacer - started
[2023-Aug-24 22:19:03.062560] INFO global - Modificator zone 13 - TownPlacer - done (4 ms)
[2023-Aug-24 22:19:03.062581] INFO global - Modificator zone 22 - TownPlacer - started
[2023-Aug-24 22:19:03.062599] INFO global - Modificator zone 19 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062629] INFO global - Modificator zone 23 - TownPlacer - started
[2023-Aug-24 22:19:03.062648] INFO global - Modificator zone 23 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062672] INFO global - Modificator zone 21 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062701] INFO global - Modificator zone 22 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062728] INFO global - Modificator zone 26 - TownPlacer - started
[2023-Aug-24 22:19:03.062681] INFO global - Modificator zone 20 - TownPlacer - started
[2023-Aug-24 22:19:03.062811] INFO global - Modificator zone 20 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062828] INFO global - Modificator zone 1 - TerrainPainter - started
[2023-Aug-24 22:19:03.062857] INFO global - Modificator zone 18 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062886] INFO global - Modificator zone 9 - TerrainPainter - started
[2023-Aug-24 22:19:03.062914] INFO global - Modificator zone 26 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062937] INFO global - Modificator zone 2 - TerrainPainter - started
[2023-Aug-24 22:19:03.062955] INFO global - Modificator zone 25 - TownPlacer - started
[2023-Aug-24 22:19:03.062981] INFO global - Modificator zone 25 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.062998] INFO global - Modificator zone 8 - TownPlacer - done (7 ms)
[2023-Aug-24 22:19:03.063030] INFO global - Modificator zone 7 - TerrainPainter - started
[2023-Aug-24 22:19:03.063032] INFO global - Modificator zone 12 - TownPlacer - done (5 ms)
[2023-Aug-24 22:19:03.063084] INFO global - Modificator zone 15 - TerrainPainter - started
[2023-Aug-24 22:19:03.063105] INFO global - Modificator zone 14 - TownPlacer - done (4 ms)
[2023-Aug-24 22:19:03.063034] INFO global - Modificator zone 6 - TerrainPainter - started
[2023-Aug-24 22:19:03.062674] INFO global - Modificator zone 24 - TownPlacer - started
[2023-Aug-24 22:19:03.063176] INFO global - Modificator zone 24 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.063195] INFO global - Modificator zone 16 - TerrainPainter - started
[2023-Aug-24 22:19:03.063178] INFO global - Modificator zone 5 - TownPlacer - done (4 ms)
[2023-Aug-24 22:19:03.063220] INFO global - Modificator zone 4 - TerrainPainter - started
[2023-Aug-24 22:19:03.063243] INFO global - Modificator zone 17 - TownPlacer - done (0 ms)
[2023-Aug-24 22:19:03.063266] INFO global - Modificator zone 11 - TerrainPainter - started
[2023-Aug-24 22:19:03.063293] INFO global - Modificator zone 3 - TerrainPainter - started
[2023-Aug-24 22:19:03.065208] INFO global - Modificator zone 1 - TerrainPainter - done (3 ms)
[2023-Aug-24 22:19:03.065233] INFO global - Modificator zone 10 - TerrainPainter - started
[2023-Aug-24 22:19:03.069544] INFO global - Modificator zone 9 - TerrainPainter - done (8 ms)
[2023-Aug-24 22:19:03.069569] INFO global - Modificator zone 13 - TerrainPainter - started
[2023-Aug-24 22:19:03.073311] INFO global - Modificator zone 2 - TerrainPainter - done (20 ms)
[2023-Aug-24 22:19:03.073331] INFO global - Modificator zone 19 - TerrainPainter - started
[2023-Aug-24 22:19:03.076443] INFO global - Modificator zone 7 - TerrainPainter - done (26 ms)
[2023-Aug-24 22:19:03.079877] INFO global - Modificator zone 23 - TerrainPainter - started
[2023-Aug-24 22:19:03.079895] INFO global - Modificator zone 15 - TerrainPainter - done (31 ms)
[2023-Aug-24 22:19:03.079913] INFO global - Modificator zone 21 - TerrainPainter - started
[2023-Aug-24 22:19:03.081586] INFO global - Modificator zone 6 - TerrainPainter - done (35 ms)
[2023-Aug-24 22:19:03.081601] INFO global - Modificator zone 22 - TerrainPainter - started
[2023-Aug-24 22:19:03.084532] INFO global - Modificator zone 16 - TerrainPainter - done (42 ms)
[2023-Aug-24 22:19:03.084561] INFO global - Modificator zone 20 - TerrainPainter - started
[2023-Aug-24 22:19:03.087990] INFO global - Modificator zone 4 - TerrainPainter - done (45 ms)
[2023-Aug-24 22:19:03.088004] INFO global - Modificator zone 18 - TerrainPainter - started
[2023-Aug-24 22:19:03.092126] INFO global - Modificator zone 11 - TerrainPainter - done (57 ms)
[2023-Aug-24 22:19:03.092141] INFO global - Modificator zone 26 - TerrainPainter - started
[2023-Aug-24 22:19:03.097284] INFO global - Modificator zone 3 - TerrainPainter - done (67 ms)
[2023-Aug-24 22:19:03.097299] INFO global - Modificator zone 25 - TerrainPainter - started
[2023-Aug-24 22:19:03.100849] INFO global - Modificator zone 10 - TerrainPainter - done (70 ms)
[2023-Aug-24 22:19:03.100880] INFO global - Modificator zone 8 - TerrainPainter - started
[2023-Aug-24 22:19:03.104035] INFO global - Modificator zone 13 - TerrainPainter - done (72 ms)
[2023-Aug-24 22:19:03.104053] INFO global - Modificator zone 12 - TerrainPainter - started
[2023-Aug-24 22:19:03.108102] INFO global - Modificator zone 19 - TerrainPainter - done (68 ms)
[2023-Aug-24 22:19:03.108116] INFO global - Modificator zone 14 - TerrainPainter - started
[2023-Aug-24 22:19:03.110413] INFO global - Modificator zone 23 - TerrainPainter - done (57 ms)
[2023-Aug-24 22:19:03.110426] INFO global - Modificator zone 24 - TerrainPainter - started
[2023-Aug-24 22:19:03.114555] INFO global - Modificator zone 21 - TerrainPainter - done (66 ms)
[2023-Aug-24 22:19:03.114572] INFO global - Modificator zone 5 - TerrainPainter - started
[2023-Aug-24 22:19:03.118260] INFO global - Modificator zone 22 - TerrainPainter - done (73 ms)
[2023-Aug-24 22:19:03.118291] INFO global - Modificator zone 17 - TerrainPainter - started
[2023-Aug-24 22:19:03.122079] INFO global - Modificator zone 20 - TerrainPainter - done (73 ms)
[2023-Aug-24 22:19:03.124820] INFO global - Modificator zone 18 - TerrainPainter - done (75 ms)
[2023-Aug-24 22:19:03.128502] INFO global - Modificator zone 26 - TerrainPainter - done (73 ms)
[2023-Aug-24 22:19:03.134120] INFO global - Modificator zone 25 - TerrainPainter - done (69 ms)
[2023-Aug-24 22:19:03.138121] INFO global - Modificator zone 8 - TerrainPainter - done (68 ms)
[2023-Aug-24 22:19:03.143234] INFO global - Modificator zone 12 - TerrainPainter - done (80 ms)
[2023-Aug-24 22:19:03.148080] INFO global - Modificator zone 14 - TerrainPainter - done (76 ms)
[2023-Aug-24 22:19:03.150502] INFO global - Modificator zone 24 - TerrainPainter - done (82 ms)
[2023-Aug-24 22:19:03.154509] INFO global - Modificator zone 5 - TerrainPainter - done (81 ms)
[2023-Aug-24 22:19:03.155844] INFO global - Modificator zone 17 - TerrainPainter - done (74 ms)
[2023-Aug-24 22:19:03.155889] INFO global - Modificator zone 2 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.155931] INFO global - Modificator zone 3 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.155994] INFO global - Modificator zone 4 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.156038] INFO global - Modificator zone 5 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.156095] INFO global - Modificator zone 6 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.156145] INFO global - Modificator zone 7 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.156167] INFO global - Modificator zone 8 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.156202] INFO global - Modificator zone 10 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.156203] INFO global - Modificator zone 9 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.156344] INFO global - Modificator zone 11 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.157168] INFO global - Modificator zone 5 - ConnectionsPlacer - done (8 ms)
[2023-Aug-24 22:19:03.157190] INFO global - Modificator zone 12 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.157319] INFO global - Modificator zone 3 - ConnectionsPlacer - done (9 ms)
[2023-Aug-24 22:19:03.157341] INFO global - Modificator zone 13 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.158496] INFO global - Modificator zone 6 - ConnectionsPlacer - done (16 ms)
[2023-Aug-24 22:19:03.158518] INFO global - Modificator zone 14 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.159019] INFO global - Modificator zone 7 - ConnectionsPlacer - done (25 ms)
[2023-Aug-24 22:19:03.159040] INFO global - Modificator zone 15 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.159354] INFO global - Modificator zone 10 - ConnectionsPlacer - done (28 ms)
[2023-Aug-24 22:19:03.159420] INFO global - Modificator zone 8 - ConnectionsPlacer - done (28 ms)
[2023-Aug-24 22:19:03.159477] INFO global - Modificator zone 16 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.159515] INFO global - Modificator zone 17 - ConnectionsPlacer - started
[2023-Aug-24 22:19:03.159981] INFO global - Modificator zone 2 - ConnectionsPlacer - done (33 ms)
[2023-Aug-24 22:19:03.160003] INFO global - Modificator zone 18 - ConnectionsPlacer - started
```

`VCMI_client.txt`:
```
[2023-Aug-24 22:17:49.673918] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.673929] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.673939] DEBUG global - Reading text from translations by key: vcmi.randomMapTab.widgets.randomTemplate
[2023-Aug-24 22:17:49.674074] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.674084] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.674092] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.674100] DEBUG global - Reading text from translations by key: vcmi.randomMapTab.widgets.randomTemplate
[2023-Aug-24 22:17:49.674153] DEBUG global - totalRedraw requested!
[2023-Aug-24 22:17:49.724649] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.724683] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.724694] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.724703] DEBUG global - Reading text from translations by key: vcmi.randomMapTab.widgets.randomTemplate
[2023-Aug-24 22:17:49.730704] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.730715] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.730722] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.730729] DEBUG global - Reading text from translations by key: vcmi.randomMapTab.widgets.randomTemplate
[2023-Aug-24 22:17:49.736333] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.736345] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.736352] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.736359] DEBUG global - Reading text from translations by key: vcmi.randomMapTab.widgets.randomTemplate
[2023-Aug-24 22:17:49.741612] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.741620] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.741626] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:49.741632] DEBUG global - Reading text from translations by key: vcmi.randomMapTab.widgets.randomTemplate
[2023-Aug-24 22:17:49.741669] DEBUG global - totalRedraw requested!
[2023-Aug-24 22:17:51.583483] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:51.583575] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:51.583594] DEBUG global - Blocking buttons
[2023-Aug-24 22:17:51.583611] DEBUG global - Reading text from translations by key: vcmi.randomMapTab.widgets.randomTemplate
[2023-Aug-24 22:17:51.583722] DEBUG global - totalRedraw requested!
[2023-Aug-24 22:18:57.699198] DEBUG global - Blocking buttons
[2023-Aug-24 22:18:57.699905] DEBUG global - Blocking buttons
[2023-Aug-24 22:18:57.699921] DEBUG global - Blocking buttons
[2023-Aug-24 22:18:57.699934] DEBUG global - Reading text from translations by key: vcmi.randomMapTab.widgets.randomTemplate
[2023-Aug-24 22:18:57.700007] DEBUG global - totalRedraw requested!
[2023-Aug-24 22:19:02.764819] ERROR global - Error: accessing unavailable frame 0:2 in CAnimation!
[2023-Aug-24 22:19:03.161424] ERROR network - Lost connection to server, ending listening thread! Connection has been closed
[2023-Aug-24 22:19:03.161907] ERROR network - Error: server failed to close correctly or crashed!
[2023-Aug-24 22:19:03.161927] ERROR network - Check /Users/mars/Library/Logs/vcmi/server_log.txt for more info
[2023-Aug-24 22:19:03.169642] DEBUG global - totalRedraw requested!
[2023-Aug-24 22:23:53.474881] INFO global - Killing console...
[2023-Aug-24 22:23:53.477247] INFO global - Killing console... done!
```

**To Reproduce**
1. Start the game from scratch (cold start);
2. Click on 'New Game' from lobby;
3. Click on 'Scenario';
4. Click on 'Random Map';
5. Choose any game options (it doesn't matter i.e: L/4/0/islands);
6. Click on 'Start'

**Expected behavior**
The first day of the first week of the main gameplay of the game should be shown.

**Actual behavior**
The game suddenly goes back to its lobby

**Did it work earlier?**
The error is strictly reproducible. This bug was not in version 1.2? _Not sure_

**Version**
 - OS: macOS ARM 13.5
 - Version: VCMI 1.3-1.4+

**Additional context**
The random game mode launches only when you restart (hot start) from the lobby (and if you exit, then starting a random game again will lead to the exit to the lobby).

**Comment by Nordsoft91** [comment] 2023-08-24 20:32
RMG crash, same as https://github.com/vcmi/vcmi/issues/2645

**Comment by gestern** [comment] 2023-08-24 21:21
> RMG crash, same as #2645

Unfortunatly, I don't see any similarities between the linked issues. First of all, for some reason **you forgot to write StR**. Secondly, the crash of the application involves closing the application, in the case I described, this does not happen. That is, they are completely different cases.

**Comment by Nordsoft91** [comment] 2023-08-26 14:06
@gestern , your logs shows server crash, which is actually closing vcmiserver application, that's why you dropped to main menu:
```
[2023-Aug-24 22:19:03.161424] ERROR network - Lost connection to server, ending listening thread! Connection has been closed
[2023-Aug-24 22:19:03.161907] ERROR network - Error: server failed to close correctly or crashed!
```

And from server logs it's obvious, that vcmiserver was crashed in the middle of random map generation:
```
[2023-Aug-24 22:19:02.770714] INFO global - Create random map.
[2023-Aug-24 22:19:02.771385] INFO global - RMG map: 108x108, WITH underground
[2023-Aug-24 22:19:02.771426] INFO global - RMG settings: players -1, teams -1, computer players -1, computer teams -1, water -1, monsters -2
[2023-Aug-24 22:19:02.771463] INFO global - RMG template name: 8MM6
[2023-Aug-24 22:19:02.771512] INFO global - Final player config: 4 total, 0 cpu-only

...

[2023-Aug-24 22:19:03.159981] INFO global - Modificator zone 2 - ConnectionsPlacer - done (33 ms)
[2023-Aug-24 22:19:03.160003] INFO global - Modificator zone 18 - ConnectionsPlacer - started
```

**Comment by gestern** [comment] 2023-08-27 00:29
@Nordsoft91 and what follows from this? You're just describing my StR. This does not prove that the two bugs are the same. 🤷‍♂️

**Comment by IvanSavenko** [comment] 2023-11-28 15:57
Unable to reproduce, presumably fixed in https://github.com/vcmi/vcmi/pull/3119

**Closed by IvanSavenko** 2023-11-28 15:57 UTC
Labels: bug, rmg
