### ISSUE TITLE
BonusList::totalValue() started returning -1 instead of 0

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1715] opened 2023-03-18 10:20 UTC
the bug seems to come from #1518 - 7e9a15c20bdd892485aba689f7c51c2bea262fc7

reproducible with Angel Wings in #1534 4a6b93968b35dcd8e7c64b7909a6e0b072d1c7ad - now movement cost is 99 instead of 100 with them, `any.indepMin` is -1, but artifact's `val` is 0, see `artifacts.json` (around line 1100).

![Screenshot 2023-03-18 at 13 04 26](https://user-images.githubusercontent.com/1557784/226099677-28a81dc7-1a49-4a9b-b5fe-1517200dd217.png)

@rilian-la-te please check

**Comment by rilian-la-te** [comment] 2023-03-18 12:18
@kambala-decapitator how many bonuses with FLYING_MOVEMENT you have?

**Comment by rilian-la-te** [comment] 2023-03-18 12:27
Looks like than something gives you FLYING_MOVEMENT bonus with INDEPENDENT_MIN=-1.

**Comment by rilian-la-te** [comment] 2023-03-18 12:38
@kambala-decapitator also please check if this bug will be fixed by https://github.com/vcmi/vcmi/pull/1716

**Comment by rilian-la-te** [comment] 2023-03-18 12:40
@kambala-decapitator and please show what is actually in bonuses container, because I cannot reproduce this for develop now.

**Closed** 2023-03-19 08:25 UTC
Labels: bug
