### ISSUE TITLE
UI error in Towns with Artifact shops and ungarrisoned heroes

### ISSUE THREAD

**Issue by storageer** [vcmi/vcmi#1761] opened 2023-03-24 16:30 UTC
**Describe the bug**
Under certain circumstances, the game UI shows buggy behaviour after visiting a Town's artifact shop.

**Game logs**
[server_log.txt](https://github.com/vcmi/vcmi/files/11064308/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/11064309/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/11064310/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/11064311/VCMI_Server_log.txt)
[Testing the Artifact Shop UI.zip](https://github.com/vcmi/vcmi/files/11064315/Testing.the.Artifact.Shop.UI.zip)

**To Reproduce**
Needs
- One Town with a built artifact shop
- One hero in town
- Optional: having several heroes on the world map makes the bug easier to notice

Steps
1. Garrison the visiting hero
2. Ungarrison the visiting hero
3. Visit the artifact shop
4. Right mouse click on the same area where the heroes would be listed on the world map
5. Bug stops triggering once the player returns to the world map and revisits the town

**Expected behavior**
The UI should work without any errors, similar to how it would with a normally visiting hero

**Actual behavior**
The UI starts showing the right click window for both the artifact shop layer and the world map layer

**Did it work earlier?**
Unknown.

**Screenshots**
Video: https://mega.nz/file/0d9WhDqI#DJjXpAL0oz5zp7ym64VpsspkQ-0vFMka9EI-TCqUOd4

**Version**
 - OS: Windows 10
 - Version: VCMI 1.1.1 release version

**Additional context**
Test map attached.

**Comment by IvanSavenko** [comment] 2023-03-24 16:33
Strictly speaking - duplicate of #1464

**Comment by storageer** [comment] 2023-03-24 16:40
Apologies, I did not find that bug when I tried to make sure I am not duplicating.

**Closed** 2023-03-25 18:02 UTC
Labels: bug
