### ISSUE TITLE
Game can't be launched if filepath contains non-unicode letters.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#865] opened 2022-09-09 05:22 UTC
It was reported many times, that VCMI doesn't launch if user's comupter has non-unicode letters or folder name contains some of them.
(https://forum.vcmi.eu/t/help-me-plss-thx/5725)

**Comment by kambala-decapitator** [comment] 2022-09-09 07:18
we should really fix such thing for 1.0

**Comment by Nordsoft91** [comment] 2022-09-09 12:47
Cannot reproduce

**Comment by kambala-decapitator** [comment] 2022-09-09 12:49
> Cannot reproduce

on which OS? The user has issue on Windows.

**Comment by Nordsoft91** [comment] 2022-09-09 12:54
Feature needs to be fixed by somebody who can reproduce.

My hypothesis about problem is that internal filesystem stores file paths as unicode.
The idea for fix is to find low-level place when files are opened (probably serialisers) and wrap strings with Unicode::toUnicode

**Comment by Nordsoft91** [comment] 2022-09-09 12:56
Also, take a look into ISimpleResourceLoader::getResourceName

**Comment by kambala-decapitator** [comment] 2022-09-10 09:14
tested the following cases on Windows 8.1 (UI language is English):

1. latin user name, symlinked `%USERNAME%\Documents\My Games\vcmi` to `C:\тест\vcmi` - all good
2. Cyrillic user name, symlinked `%USERNAME%\Documents\My Games\vcmi` to `D:\vcmi` - client starts fine, attempt to start server for new scenario crashes (on the Connecting... dialog). Client continues to operate. After a few more attempts client crashes as well, in logs there's "Disaster happened" and "access violation".

Last console messages:

> [green] Initialization of VCMI (together) ...
> [normal] The system cannot find the path specified
> [red] Error: server failed to close correctly or crashed!
> [red] Check ...\server_log.txt for more info (remark: user name symbols resemble broken UTF-8)

Unfortunately, server log isn't even created in this case.

If I start server executable manually, there're no error messages.

Will now try to fix the code.

**Closed** 2022-09-11 09:04 UTC
Labels: bug
