### ISSUE TITLE
The AI hero enters the battle while on the water with the hero on land. After that the game crashes

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#903] opened 2022-09-14 21:04 UTC
![002](https://user-images.githubusercontent.com/36762538/190261216-9c2fafb2-084f-49d6-9153-aa60ac92be55.png)
[Bug.zip](https://github.com/vcmi/vcmi/files/9569917/Bug.zip)

The pink hero Torosar attacks the green Cyra

(press end turn)

**Comment by nullkiller** [comment] 2022-09-16 14:00
Looks like duplicate of https://github.com/vcmi/vcmi/issues/844

**Closed by nullkiller** 2022-09-16 14:00 UTC
