### ISSUE TITLE
the game crashes after a certain number of moves from the start of the game. regardless of map or capmania. ALL TIME

### ISSUE THREAD

**Issue by veerus3d** [vcmi/vcmi#3329] opened 2023-12-16 21:36 UTC
Process:               vcmiclient [5215]
Path:                  /Applications/VCMI.app/Contents/MacOS/vcmiclient
Identifier:            vcmiclient
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-16 23:31:39.9671 +0200
OS Version:            macOS 14.2 (23C64)
Report Version:        12
Anonymous UUID:        41FF0E89-9D8D-9221-67F3-CA840FA18279

Time Awake Since Boot: 23000 seconds

System Integrity Protection: enabled

Crashed Thread:        3  Dispatch queue: com.Metal.CompletionQueueDispatch

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000018a32b60c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [5215]

**Comment by kambala-decapitator** [comment] 2023-12-17 05:20
the posted info isn't very useful without at least stacktrace of the crashed thread

also looks like duplicate of #3269

**Closed by kambala-decapitator** 2023-12-17 05:20 UTC
Labels: bug

**Comment by muchitto** [comment] 2023-12-20 17:10
Happens to me too.

I got M2 Pro Macbook, MacOS 14.2.1 

My logs:

[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13730192/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13730194/VCMI_Server_log.txt)

https://github.com/vcmi/vcmi/assets/359786/0379f1a3-59a8-4588-9499-4cc8cdbb9964



https://github.com/vcmi/vcmi/assets/359786/43cd7acd-74ce-4d11-a2fa-76335cf39ef2
