### ISSUE TITLE
Current save file is not highlighted 

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2137] opened 2023-05-07 00:09 UTC
**Describe the bug**
See video

**Expected behavior**
Selected save is highlighted

**Actual behavior**
Some save is highlighted unpredictively

**Did it work earlier?**
Yes

**Screenshots**

https://user-images.githubusercontent.com/9308612/236651280-2c01116c-9ebf-4b88-b758-bf50579f1b10.mp4

**Version**
 - OS: [e.g. Windows, macOS Intel, macOS ARM, Android, Linux, iOS]
 - Version: [VCMI version]

**Additional context**

**Comment by kambala-decapitator** [comment] 2023-05-07 07:34
seems duplicate of #1371

**Closed** 2023-07-13 09:57 UTC
Labels: bug, client
