### ISSUE TITLE
You will lost the bonus if you load the game and then restart the game.

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi/vcmi#2693] opened 2023-08-28 06:00 UTC
1. Choosing a bonus and starting the scenario, and then you touch the "restart the scenario" button, it runs very well.
2. Choosing a bonus and starting the scenario, at this time you save this scenario, and then you load the scenario and touch the "restart the scenario" button, you will find: you lost the starting bonus.

By the way, in the scenario "Pandora's box" the hero "Perseus" who has specialty "Ballistic" doesn't have a ballistic.

**Comment by IvanSavenko** [comment] 2023-08-28 08:01
Which map or campaigns should I use?
Which bonus should I choose?
What game version are you using?

**Comment by lishaoxia1985** [comment] 2023-08-28 10:02
vcmi  is 1.3.1, game is heroes iii complete. It apears in all the scenario, such as the first map of "Elixir of Life".

**Comment by IvanSavenko** [comment] 2024-01-31 11:00
Closing, unable to reproduce in both 1.4 and current 1.5 build.

In first scenario of Elixir of Life Gelu correctly receives starting bonus even when restarting loaded game.

**Closed by IvanSavenko** 2024-01-31 11:00 UTC
Labels: bug, campaigns
