### ISSUE TITLE
Keeps crashing on MacOS 14.2 when going into the castle

### ISSUE THREAD

**Issue by pyemus** [vcmi/vcmi#3317] opened 2023-12-15 09:19 UTC
**Describe the bug**
First of all, thank for you for making VCMI! Its awesome.
I have some issues on the latest MacOS Sonoma 14.2. When I click into the castle (some the sidebar) it crashes completely. I have tried a few times and never made it through the first day because it crashes :-( 

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.
[server_log.txt](https://github.com/vcmi/vcmi/files/13683314/server_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/13683315/VCMI_Client_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13683316/VCMI_Server_log.txt)

**To Reproduce**
1. Start any singleplayer map
2. walk around with the hero 
3. Click on the map in the sidebar
4. I get a crash

**Did it work earlier?**
This is the first time i try VCMI...so i don't know

**Screenshots**
<img width="1006" alt="image" src="https://github.com/vcmi/vcmi/assets/2339329/fca23ea8-aa63-4def-a0be-a1bb8665f2e5">
<img width="242" alt="image" src="https://github.com/vcmi/vcmi/assets/2339329/e29d0f41-d7f0-4997-98d9-3defe7b8a51e">

**Version**
 - OS: 14.2 MacOS
 - Version: 
<img width="962" alt="image" src="https://github.com/vcmi/vcmi/assets/2339329/9290a031-bbeb-4bf0-9940-d9147e4b76f1">

**Comment by kambala-decapitator** [comment] 2023-12-15 09:49
duplicate of #3269

**Closed by kambala-decapitator** 2023-12-15 09:49 UTC
Labels: bug
