### ISSUE TITLE
Cannot update a mod if another mod has a dependency on it

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4727] opened 2024-10-05 08:33 UTC
**Describe the bug**
I have 2 mods. Forge2k that depends on Asphalt Terrain. I cannot update Asphalt terrain unless I manually disable Forge2k.

For other mod collections (like PVP balance) the scenario is more complicated, because there are more dependencies.

**Version**
 - OS: [e.g. Windows
 - Version: [VCMI version] 1.5.7

**Comment by IvanSavenko** [comment] 2024-10-15 16:26
Duplicate of #2046

**Closed by IvanSavenko** 2024-10-15 16:26 UTC
Labels: bug, launcher
