### ISSUE TITLE
Nullkiller AI crash

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#1330] opened 2022-12-27 23:54 UTC
**Describe the bug**
Game crashes during AI turn with Nullkiller AI. Mods used: VCMI Extras

**Game logs**
Please attach game logs: https://www.mediafire.com/file/2c65o1muoz45hpe/aicrash.zip/file

**To Reproduce**
1. Try pass bunch of turns with provided save until AI crashes - if AI doesn't crash within let's say 10 turns then reload save and try again

**Expected behavior**
Game not crashing

**Actual behavior**
Game crashes during AI turn

**Did it work earlier?**
N/A

**Version**
 - OS: Kubuntu 22.04
 - Version: Current develop branch

**Additional context**
Message in console when crash occurs: vcmiclient: ./AI/Nullkiller/AIUtility.cpp:112: const CGHeroInstance* NKAI::HeroPtr::get(bool) const: Assertion `obj' failed.

EDIT:
Also reproducible in VCMI 1.1.0 - I get consistent crashes within few turns on S size armageddon's blade map with 8 players (forgot english name), last camera position before crash was enemy hero at experience stone

EDIT2: map name is Elbow Room - 3 map restarts, i got 3 crashes within 5 turns after using vcmiglaurung and vcmieagles cheats to spectate in peace

**Comment by nullkiller** [comment] 2022-12-28 12:54
assertions disabled in release. Can you confirm that it crashes with other kind of error in this case? Because sometimes it works. /it does not mean assertions are useless but it may reduce the urgency of this fix

**Comment by dydzio0614** [comment] 2022-12-29 15:56
For some reason I didn't think about why i get asserts in downloaded build for ubuntu PPA... so primary problem is with linux repo having asserts in build

**Comment by IvanSavenko** [comment] 2023-03-10 19:49
Update: this is no longer an assert, but this is still (potential) bug in AI, that results in error message to console now

**Comment by nullkiller** [comment] 2023-11-03 17:57
Sad that there is no details. If it is about AI attempt to access removed objects it is mostly ok.

**Comment by IvanSavenko** [comment] 2023-11-03 19:12
Not sure if this happens in 1.4, but when I have investigated it was caused by losing main hero in battle and then - attempting to access it.

**Comment by IvanSavenko** [comment] 2024-04-11 19:59
Closing, old and not reproducible. Feel free to reopen if this might still be relevant.

**Closed by IvanSavenko** 2024-04-11 20:00 UTC
Labels: bug, nullkillerai
