### ISSUE TITLE
Crash in battle

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4060] opened 2024-05-30 11:57 UTC
Green AI attacked titans and crash has happened

save [1.zip](https://github.com/vcmi/vcmi/files/15499331/1.zip)

dump https://drive.google.com/file/d/1sApcK3YnHEMsKyyOpaXWjh3ayS3YnxpP/view?usp=drive_link

> ERROR [AIGateway::makeTurn] global - Cannot find info for team -1

1.5.2.5c2ca380abad88591d497637adf846f3ca762c39, msvs
***
[crashMaster.zip](https://github.com/user-attachments/files/15511720/crashMaster.zip)
looks like very similar (master 1.5.2)

**Comment by IvanSavenko** [comment] 2024-05-31 21:23
@nullkiller Looks like hero was defeated (owner == -1) but AI is still trying to explore with this hero.

I think I saw similar bug before 1.5.2 with VCAI, so probably caused by porting of VCAI logic
```
VCMI_lib.dll!PathfinderUtil::evaluateAccessibility<0>(const int3 & pos, const TerrainTile & tinfo, const std::unique_ptr<boost::multi_array<unsigned char,3,std::allocator<unsigned char>>,std::default_delete<boost::multi_array<unsigned char,3,std::allocator<unsigned char>>>> & fow, const PlayerColor player, const CGameState * gs) Line 28	C++
VCMI_lib.dll!NodeStorage::initialize(const PathfinderOptions & options, const CGameState * gs) Line 54	C++
VCMI_lib.dll!CPathfinder::CPathfinder(CGameState * _gs, std::shared_ptr<PathfinderConfig> config) Line 79	C++
VCMI_lib.dll!CGameState::calculatePaths(const std::shared_ptr<PathfinderConfig> & config) Line 1182	C++
VCMI_lib.dll!CGameState::calculatePaths(const CGHeroInstance * hero, CPathsInfo & out) Line 1176	C++
VCMI_client.exe!CClient::getPathsInfo(const CGHeroInstance * h) Line 700	C++
VCMI_client.exe!CCallback::getPathsInfo(const CGHeroInstance * h) Line 347	C++
[Inline Frame] Nullkiller.dll!NKAI::Goals::ExploreNeighbourTile::accept::__l4::<lambda_f99ee6153f542034a6f9d87409591bd9>::operator()(int3) Line 38	C++
Nullkiller.dll!NKAI::foreach_neighbour<<lambda_f99ee6153f542034a6f9d87409591bd9>>(const int3 & pos, const NKAI::Goals::ExploreNeighbourTile::accept::__l4::<lambda_f99ee6153f542034a6f9d87409591bd9> & foo) Line 210	C++
Nullkiller.dll!NKAI::Goals::ExploreNeighbourTile::accept(NKAI::AIGateway * ai) Line 57	C++
Nullkiller.dll!NKAI::Goals::Composition::accept(NKAI::AIGateway * ai) Line 53	C++
Nullkiller.dll!NKAI::Nullkiller::executeTask(std::shared_ptr<NKAI::Goals::ITask> task) Line 526	C++
Nullkiller.dll!NKAI::Nullkiller::makeTurn() Line 467	C++
Nullkiller.dll!NKAI::AIGateway::makeTurn() Line 856	C++
boost_thread-vc143-mt-x64-1_81.dll!00007ffb5fbe8a5a()	Unknown
ucrtbase.dll!thread_start<unsigned int (__cdecl*)(void *),1>()	Unknown
kernel32.dll!BaseThreadInitThunk()	Unknown
ntdll.dll!RtlUserThreadStart()	Unknown
```

**Comment by IvanSavenko** [comment] 2024-05-31 21:39
Yeah, duplicate of #4066
So closing this one.

**Closed by IvanSavenko** 2024-05-31 21:39 UTC
Labels: bug
