### ISSUE TITLE
duplicate hero from prison

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#2299] opened 2023-07-08 10:59 UTC
template: Jebus Cross
mods: HotA, Campaign heroes

reported in the [VK group](https://vk.com/topic-83330735_33209453?post=714)

![image](https://github.com/vcmi/vcmi/assets/1557784/590f9c95-b10f-42b8-a307-53de3db90672)

**Comment by DjWarmonger** [comment] 2023-07-08 14:52
Is that 1.2, or any recent build?

**Comment by dydzio0614** [comment] 2023-07-08 14:58
since it's mobile it's highly likely this is from 1.2

**Comment by DjWarmonger** [comment] 2023-07-09 14:12
Prisons were not distributed correctly in 1.2. Not sure if that was the cause, but most likely it may behave differently in daily build.

**Comment by IvanSavenko** [comment] 2024-02-05 20:35
Presumably fixed in one of 1.4 hotfixes?
With my starting hero fix and @DjWarmonger fix for hero banning this should no longer happen.
I also don't see people reporting this anymore, in one form or another, and no more crashes on Google Play that were clearly caused by hero duplication.

**Closed by IvanSavenko** 2024-02-05 20:36 UTC
Labels: bug, modding, rmg
