### ISSUE TITLE
Fail to show messages in hota mod

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2615] opened 2023-08-18 13:47 UTC
**Describe the bug**
Resource Warehouses showed wrong information while on visiting and visited.

**To Reproduce**
1. Install hota mod.
2. Go to a random map with resource warehouses.
3. Save and load, then restart the map,
4. See error in message while visiting a warehouse..

**Did it work earlier?**
No, never worked.

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/127420617/4b82d178-bfac-4ef5-bf60-1fd9071ab382)

**Version**
 - OS: Windows
 - Version: 1.40

**Comment by IvanSavenko** [comment] 2023-11-28 15:56
Unable to reproduce on current beta.

**Comment by IvanSavenko** [comment] 2024-01-06 11:42
Closing, unable to reproduce and have not seen anybody else reporting such issue.

Please reopen if this still happens for you and upload logs

**Closed by IvanSavenko** 2024-01-06 11:42 UTC
Labels: bug, modding
