### ISSUE TITLE
No audio for 3DO intro

### ISSUE THREAD

**Issue by cewbdex** [vcmi/vcmi#2760] opened 2023-09-05 10:35 UTC
**Describe the bug**
I don't have audio playing for the game "3DO" intro. After skipping the intro, main menu music plays fine.

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12522375/VCMI_Client_log.txt)

**To Reproduce**
1. Start the game

**Expected behavior**
Intro plays with audio

**Actual behavior**
Intro plays without audio.

**Did it work earlier?**
No

**Screenshots**
N/A, video if you request, but I think the description is self-explanatory.

**Version**
 - OS: Fedora 38
 - Version: 1.3.1

**Additional context**
N/A

**Comment by ghd987654321** [comment] 2023-09-05 12:23
Duplicate of #1992

**Comment by IvanSavenko** [comment] 2023-09-05 12:25
No, it is not the same issue.

Campaign videos actually don't have sound. Instead they have separate music track and separate voice-over track.
Missing feature since we don't use that info right now.

**Comment by Laserlicht** [comment] 2023-09-11 17:22
The CVideoHandler currently reads out only the video stream. The audio stream is ignored.

It's an completely independent issue.

**Closed** 2023-10-09 22:40 UTC
Labels: bug
