### ISSUE TITLE
Need to press key twice

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2193] opened 2023-05-28 00:47 UTC
Start any scenario with welcome message (e.g. day 0 message)
Press return to close window

**Expected behavior**
Window is closed

**Actual behavior**
Window is not closed - need to press enter again.

**Comment by IvanSavenko** [comment] 2023-06-05 19:28
I *might* have found this but seems to be happening only when activating a window and only with mouse click, not with keyboard.

If this is same scenario as yours - then will be fixed soon - default SDL behavior, but can be changed.

**Comment by IvanSavenko** [comment] 2023-07-05 15:35
Very unstable reproducibility. Happens only *sometimes*, but not idea what's the trigger.

Will fix if manage to reproduce it again or if somebody manages to find more reliable repro

**Closed** 2023-07-15 18:55 UTC
Labels: bug, client
