### ISSUE TITLE
Win in defend town but lose the town.

### ISSUE THREAD

**Issue by tranhoangnguyen193** [vcmi/vcmi#3653] opened 2024-03-04 10:11 UTC
**Describe the bug**
I played as player 3 (green). It is the turn of player 5 (purple). Purple win the quick combat, I saw that the town is disappeared from my screen. I replay the combat and win but my town still lose to player 5. After that I seige that town again and see that I'm control the town and combat with another "me"

**Game logs**
Why do I want to move hero Fiur to tile (63 2 0)? Already standing on that tile! 

Hero Luna has 1760 MP left

Hero Orrin has 546 MP left

Hero Thunar has 1700 MP left

Hero Tyris has 330 MP left

Player 4 (orange) ends turn

Player 5 (purple) starting turn, day 22

Player 4 (orange) ended turn

Opening BattleAI

Loaded Battle AI

Opening BattleAI

Loaded Battle AI

Opening BattleAI

Loaded Battle AI

Call to loadBitmap with void fname!

Error: failed to load image 

Animation  failed to load

GetImage error: Request for frame not present in CAnimation! File name: SPRITES/, Group: 0, Frame: 0

Shooting animation has finished but projectile was not emitted! Emitting it now...

Cannot get object with id 9959. Object was removed

Cannot get object with id 9959. Object was removed

Hero Tamika was lost. Exit hero chain.

You were identified as player 5 while expecting 3

Player is not allowed to perform this action!

Got false in applying 8MoveHero... that request must have been fishy!

System message: You were identified as player 5 while expecting 3

System message: You are not allowed to perform this action!

System message: Server encountered a problem: Got false in applying 8MoveHero... that request must have been fishy!

virtual void CGameInfoCallback::fillUpgradeInfo(const CArmedInstance*, SlotID, UpgradeInfo&) const: Cannot get info about not owned object!

virtual void CGameInfoCallback::fillUpgradeInfo(const CArmedInstance*, SlotID, UpgradeInfo&) const: Cannot get info about not owned object!

virtual void CGameInfoCallback::fillUpgradeInfo(const CArmedInstance*, SlotID, UpgradeInfo&) const: Cannot get info about not owned object!

virtual void CGameInfoCallback::fillUpgradeInfo(const CArmedInstance*, SlotID, UpgradeInfo&) const: Cannot get info about not owned object!

virtual void CGameInfoCallback::fillUpgradeInfo(const CArmedInstance*, SlotID, UpgradeInfo&) const: Cannot get info about not owned object!

Player 5 (purple) ends turn

Player 6 (teal) starting turn, day 22

Player 5 (purple) ended turn

Opening BattleAI

Loaded Battle AI

**To Reproduce**
1. Stay in your town, wait for other player seige it
2. The other player win the quick combat. Then replay
3. Win the replay combat
4. See that your town is lost.

**Expected behavior**
Your town do not lose.

**Actual behavior**
Your town lost

**Comment by IvanSavenko** [comment] 2024-03-04 11:18
- Duplicate of #3608
- Should be fixed by #3644

**Closed** 2024-03-07 08:49 UTC
Labels: bug
