### ISSUE TITLE
School of Magic image is cut

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1384] opened 2023-01-07 08:58 UTC
Normally the image is correct, but in this specific case it's cut in the bottom. Dunno if it's the same in oh3.

![Screen Shot 2023-01-06 at 21 40 15](https://user-images.githubusercontent.com/1557784/211142490-2cd8c6bd-5af4-462b-a331-510ae59043dd.png) ![Screen Shot 2023-01-06 at 21 40 24](https://user-images.githubusercontent.com/1557784/211142494-59efe07b-5a40-44c6-adb1-cb26f85f06c5.png)

**Comment by rilian-la-te** [comment] 2023-03-13 11:26
@IvanSavenko is this fixed by new renderer?

**Comment by IvanSavenko** [comment] 2023-03-13 11:29
Not sure whether this is bug actually.
@kambala-decapitator do you remember map where this happened? H3 map or RMG?

**Comment by kambala-decapitator** [comment] 2023-03-13 11:33
RMG

**Comment by IvanSavenko** [comment] 2023-03-13 11:46
Not a bug. 
H3 allows same placement and also produces identical result. It also matches H3 rules for object placement.

**Closed** 2023-03-13 11:46 UTC
Labels: bug, client
