### ISSUE TITLE
Blue square on loading screen MacOS ARM

### ISSUE THREAD

**Issue by herve-ch** [vcmi/vcmi#3890] opened 2024-05-05 09:34 UTC
**Describe the bug**
When I load a game I got a blue square on the screen, see screenshot

**Expected behavior**
No blue square

**Actual behavior**
A big blue square appears in loading screen 

**Did it work earlier?**
I did not find any version without this bug

**Screenshots**
<img width="979" alt="Capture d’écran 2024-05-04 à 23 28 57" src="https://github.com/vcmi/vcmi/assets/53587445/8f42da54-a735-4285-b246-760cc10d2c02">

**Version**
 - OS: macOS M1
 - Version: latest beta 6ac6777

**Additional context**
It happens with all versions

**Comment by kambala-decapitator** [comment] 2024-05-05 09:45
doesn't happen on an Intel Mac, will check on ARM tomorrow

**Comment by IvanSavenko** [comment] 2024-05-05 09:48
May be caused by (French?) translation mod

**Comment by herve-ch** [comment] 2024-05-05 09:52
You are right! I just uninstalled the French translation and it works. That's strange, the translation change main  background image also

**Comment by IvanSavenko** [comment] 2024-05-05 09:54
Can check that mod, but yeah.

In H3 some text is embedded into images. Buttons in main menu for example. Another one is that "Nom du scenario" text from your screenshot.

Because of that translation mods also come with some images that translate such texts. And it looks like this particular image is broken in this mod.

**Comment by herve-ch** [comment] 2024-05-05 09:55
ok I understand now, thanks a lot!

**Comment by IvanSavenko** [comment] 2024-05-06 12:06
Mod should be fixed. Please update french translation in launcher to get new version.

**Comment by IvanSavenko** [comment] 2024-05-06 20:53
Closing, please reopen if it happens again

**Closed by IvanSavenko** 2024-05-06 20:53 UTC
Labels: bug
