### ISSUE TITLE
Crash after attacking Diamond Dragons

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#1903] opened 2023-04-07 18:52 UTC
**Describe the bug**
I attacked a stack of Diamond Dragons and they retaliated, then game crashed. No visual indication of anything going wrong on the battlefield, image just froze.

**Game logs**
[CrashDiamondDragons.zip](https://github.com/vcmi/vcmi/files/11180837/CrashDiamondDragons.zip)

**To Reproduce**
Enable wog mod ang generate Clash of Dragons template (XL + U), Diamond Dragons will surely spawn in treasure zones.

**Did it work earlier?**
If this something which worked well some time ago, please let us know about version where it works or at date when it worked.

**Screenshots**
<img width="1240" alt="Crash with Diamond Dragons" src="https://user-images.githubusercontent.com/2566990/230661895-789bbf77-51fa-4e6d-b445-e9d2e5e2230d.png">

**Version**
Beta
WoG with "Graphic fix" submod enabled.

**Comment by IvanSavenko** [comment] 2023-04-08 16:01
Unable to reproduce
- wog enabled
- crystal dragons found
- was able to fight them & win the battle without crashes

**Comment by IvanSavenko** [comment] 2023-04-08 16:03
Might actually be duplicate of #1907 
I have fix for it in my branch and crystal dragons apply effect (blind) on counter

**Comment by IvanSavenko** [comment] 2024-04-11 19:58
Closing, old and not reproducible. Feel free to reopen if this might still be relevant.

**Closed by IvanSavenko** 2024-04-11 19:58 UTC
Labels: bug, battle
