### ISSUE TITLE
RMG Incomplete buildings appear when placed too close to top map border

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1927] opened 2023-04-09 22:22 UTC
**Describe the bug**
Buildings look ugly an unfinished if spawned near top border

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/230799228-aa87528b-9167-4f66-b9ad-b53c3e37c22b.png)

Building size should matter when placed near top border.

**Comment by IvanSavenko** [comment] 2023-04-09 22:32
@krs feel free to find road adjacent to map border and post another amazing screenshot

**Comment by Nordsoft91** [comment] 2023-04-10 00:05
but what is expected behavior? I suppose that drawing on the top of map border will look much worse...

**Comment by krs0** [comment] 2023-04-10 07:46
Each building has a footprint... check that footprint falls completely inside map.

**Comment by Nordsoft91** [comment] 2023-04-10 13:40
that's what we do, but we are taking tiles blocked by building.
Otherwise you will have space between object and map edge where hero can move freely so generated maps will have catastrophic imbalance.
How is it handled in OH3?

**Comment by Nordsoft91** [comment] 2023-04-10 13:43
I suggest wont fix because visible not-blocked tiles don't impact game logic at all. They are purely visual.
You basically suggesting to break this logic and introduce real game logic dependency from visual stuff

**Comment by IvanSavenko** [comment] 2023-04-10 13:47
It does not impacts game logic but certainly affects visual experience. Using same logic - why bother with nice obstacle generation when we can simply fill that area with single-tile trees?
After all, this does not impact game logic at all!

Maybe reserve top 1-2 rows and simply don't place any visitable, non-pickable objects in there?
Static obstacles are fine, various resource piles are fine. But visitable objects should be excluded from top rows

It looks that in H3 such situation is impossible by the way.

**Comment by Nordsoft91** [comment] 2023-04-10 14:05
> why bother with nice obstacle generation when we can simply fill that area with single-tile trees?

We don't. We place random objects to cover space we want to cover. If modder created only one picture with single tree - then only one will be used.

You basically suggest to reduce maps size from 36x36 to 36x34 which contradicts to oh3.

And take a look on the picture...
<img width="478" alt="Снимок экрана 2023-04-10 в 18 03 29" src="https://user-images.githubusercontent.com/9308612/230916750-f6296dba-799a-48a8-9c7b-93a0428fa5d6.png">

**Comment by IvanSavenko** [comment] 2023-04-10 14:09
> You basically suggest to reduce maps size from 36x36 to 36x34 which contradicts to oh3.

Does it?

![зображення](https://user-images.githubusercontent.com/1576820/230917367-87d060ea-bca8-4d4b-aa15-e4836456737a.png)

![зображення](https://user-images.githubusercontent.com/1576820/230917761-e237717a-25cb-47b0-b284-71199dc94e2a.png)

This is H3 RMG.
So far I found 0 cases where image of a non-static object is obstructed by top border

**Comment by dydzio0614** [comment] 2023-04-10 14:16
next ticket from krs0: "add map editor warning when placing object on top row because it looks ugly and incomplete" :P

**Comment by Nordsoft91** [comment] 2023-04-10 14:17
If it's OH3 behavior, then I agree

**Comment by dydzio0614** [comment] 2023-04-10 14:19
im neutral, but reserving 2 top rows wont work for towns, dragon utopias etc... and may negatively impact optimal object placement

**Comment by DjWarmonger** [comment] 2023-04-10 14:42
We can easily get the object bounds from the template, it is not a big issue.

**Comment by DjWarmonger** [comment] 2023-04-10 14:47
Even if tall objects won't make it, I guess the space by the top of the map will be filled by resources and one-tile objects anyway. It shouldn't be game-breaking.

**Comment by krs0** [comment] 2023-04-10 16:29
![image](https://user-images.githubusercontent.com/15194321/230945904-a8904803-a1e1-4c08-a253-9d5685049d2d.png) ![image](https://user-images.githubusercontent.com/15194321/230945921-31e058a1-9f80-44f5-a922-bf5ae746a997.png) and especially! ![image](https://user-images.githubusercontent.com/15194321/230946034-3e01f781-cbab-4e65-9ba2-90c6289a6da2.png) are thanking you :D

**Comment by DjWarmonger** [comment] 2023-04-10 17:24
Got this:
![image](https://user-images.githubusercontent.com/2566990/230955975-40edbc2f-23ad-4efc-867a-984315ebf26f.png)
![image](https://user-images.githubusercontent.com/2566990/230956135-f69ef32a-1dea-43fc-a19e-9cb6e6caa1e1.png)

**Comment by IvanSavenko** [comment] 2023-04-10 17:28
@DjWarmonger 
Look great! Things to consider:
- How Dragon Utopia / towns will look like?
- Roads should not be placed next to map edge - see graphical glitch on left side of 2nd image

**Comment by DjWarmonger** [comment] 2023-04-10 17:42
All objects are checked for their actual height. Dragon Utopia will just work as well.

As to roads - completely different issue. I don't even think it's the problem with RMG itself, maybe with draw road operation.

**Comment by krs0** [comment] 2023-04-10 18:06
Anyway a road should not appear on top row, because hero sprite is 2 tiles high!
Maybe we allow this for Halloween :)

**Comment by krs0** [comment] 2023-04-10 18:23
As for road spikes... there should be no roads that do not end with an object... or another road.

**Comment by IvanSavenko** [comment] 2023-04-10 18:24
> As to roads - completely different issue. I don't even think it's the problem with RMG itself, maybe with draw road operation.

Sure, as long as you're aware of it.

> Anyway a road should not appear on top row, because hero sprite is 2 tiles high!

Makes sense, but road bug also happens on sides of the map.

**Closed** 2023-04-11 08:41 UTC
Labels: bug, rmg
