### ISSUE TITLE
RMG maps for Jebus Cross use "same" template most of the time

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#4373] opened 2024-08-03 13:51 UTC
**Describe the bug**
Jebus Cross random maps are very often generated with straight line roads and end up looking a lot of times like an inversed "T", with all cities in same position across multiple map generations.

Would be nice to have more variation in road and town placement.

**Comment by dydzio0614** [comment] 2024-08-03 14:22
town placement is expected to stay the same and was delibarately done that was as part of pvp players requests
road placement - yeah, i agree with you

**Comment by DjWarmonger** [comment] 2024-09-15 19:20
Jebus works as intended. Straight roads will be fixed as a separate issue.

**Closed** 2024-09-15 19:20 UTC
Labels: bug, rmg
