### ISSUE TITLE
Campaign intro video not playing voicover

### ISSUE THREAD

**Issue by peterpaulis** [vcmi/vcmi#2448] opened 2023-07-30 19:37 UTC
**Describe the bug**
No voice-over is played during campaign intro video... thats from the original where voice-over is present
https://www.youtube.com/watch?v=z5b0iyPGqNM
however just the music is played in VCMI

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.

**To Reproduce**
1. Go to Campaigns
2. Pick any campaign
3. The campaign video stars, but no voiceover is heard

**Expected behavior**
As in original, the voiceover should be played

**Actual behavior**
No voiceover is heard

**Did it work earlier?**
Dont know

**Screenshots**
<img width="1460" alt="Screenshot 2023-07-30 at 21 37 33" src="https://github.com/vcmi/vcmi/assets/1956972/1c869c5d-eb38-4f90-80e4-395d2e2dfc4b">

**Version**
 - OS: macOS
 - Version: 1.2

**Additional context**
none

**Comment by IvanSavenko** [comment] 2023-07-30 19:39
Duplicate of #1992

**Closed by IvanSavenko** 2023-07-30 19:39 UTC
Labels: bug, campaigns
