### ISSUE TITLE
Can't launch generated random map

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3295] opened 2023-12-10 18:57 UTC
**Describe the bug**
Once generated random map cannot be launched - There's some issue with heroes.

**Game logs**
Hero is already on the map at (75 42 0)

**To Reproduce**
Unpack this map:
https://github.com/vcmi/vcmi/issues/3294

Launch the map with no mods (makes no difference as far as I see)

**Expected behavior**
Map would launch as usual

**Actual behavior**
Instant server crash

**Screenshots**
Looks like Grid sitting in prison at these coordinates is not banned on the map, none of imprisoned heroes are.
![Uploading Gird not banned on random map.png…]()

**Comment by DjWarmonger** [comment] 2024-01-18 19:19
Some clues from Discord channel: loaded map has multiple Prisons with subID 0, which ich wrong. Every Prison should have unique subID, and 0 is id of Orrin.
[MapWithPrisons.zip](https://github.com/vcmi/vcmi/files/13980833/MapWithPrisons.zip)

**Comment by Warzyw647** [comment] 2024-01-21 10:07
Another clue from the map editor. Screens from the current version (minus some rmg fixes).
Object inspector for a new hero on a new map. Picking a different name from the list in field Hero type changes SubID:
![newHero](https://github.com/vcmi/vcmi/assets/132299608/d4f6cb7f-da47-4093-a004-2c3cdab4be29)
object inspector for a new prison on a new map:
![newPrison](https://github.com/vcmi/vcmi/assets/132299608/a91dc239-44d7-42bb-8321-a6a3a03bd648)
and object inspector for a prison containing Neela on a SoD map opened in VCMI map editor:
![prisonFromSodMap](https://github.com/vcmi/vcmi/assets/132299608/d175f4d3-b722-4b06-bd15-a239628b7427)

**Comment by godric3** [comment] 2024-01-28 18:35
Not only prisons cause this problem, I tired to load Antagarich Burning maps. First they don't load due to `'torosar '` hero name that was changes some time ago. After fixing that map crashes with same error (Hero is already on the map ).
Can be reproduced with creating map with two heroes of same class (two knight). Two heroes of different classes won't trigger this crash.
Test map(rename to .vmap)
[HeroOnMap.zip](https://github.com/vcmi/vcmi/files/14077295/HeroOnMap.zip)

Looking into jsons it looks fine:
```
"hero_0" : {
		"l" : 0,
		"options" : {
			"experience" : 9223372036854775807,
			"owner" : "red",
			"type" : "core:edric"
		},
		"subtype" : "knight",
		"template" : {
			...
		},
		"type" : "hero",
		"x" : 7,
		"y" : 9
	},
```
Specific hero info is in options, but seems like there is problem with reading that during map loading. Could it be that it uses `"subtype" : "knight"` instead of `"type" : "core:edric"` for subID?

**Comment by IvanSavenko** [comment] 2024-02-05 20:33
Thanks for research @godric3 
Looks like duplicate hero check was performed before sub ID is properly initialized, leading to these false-positive.
In my PR I was able to load both Antagarich Burning and old random maps that were generating duplicate hero errors before.
So should be fixed

**Closed** 2024-02-06 22:16 UTC
Labels: bug, rmg
