### ISSUE TITLE
NKAI ally reveals map for player

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1059] opened 2022-10-08 01:52 UTC
Allies have a common map visibility map NKAI uses cheat vcmieagles so map becomes visible to player

**Comment by nullkiller** [comment] 2022-10-30 09:58
What if we have two different settings same as we have for battle AI so that we can set VCAI for ally and Nullkiller for enemy?

**Comment by DjWarmonger** [comment] 2023-03-02 14:56
Sounds like it's not a bug, it's a feature ¯\_(ツ)_/¯

You can always see everything your allies can see.
If you don't want to have map revealed, don't play withy allies.

**Comment by rilian-la-te** [comment] 2023-03-02 14:59
@DjWarmonger we can add json settings to nkai, if we really want NKAI not use vcmieagles.

**Comment by nullkiller** [comment] 2023-07-24 19:02
Now it should be possible to use VCAI as friendly AI. @IvanSavenko?

**Comment by IvanSavenko** [comment] 2023-07-24 19:17
Yes. So closing as resolved I guess? By default allies use VCAI so shouldn't be a problem normally.

**Closed by IvanSavenko** 2023-07-24 19:17 UTC
Labels: bug, nullkillerai, visibility
