### ISSUE TITLE
Bug:Can't equip artifacts

### ISSUE THREAD

**Issue by LordIofIThunder** [vcmi/vcmi#2985] opened 2023-09-30 09:00 UTC
https://youtube.com/watch?v=UulEBKwwqRg&feature=shared

**Comment by SoundSSGood** [comment] 2023-09-30 10:42
save files?

**Comment by LordIofIThunder** [comment] 2023-09-30 12:09
Unfotunately i didn't saved that game but i have another one with the same problem.
https://www.mediafire.com/file/dvec4alcspzgx7t/primary_Android_data_is.xyz.vcmi.daily_files_vcmi-data_Saves_Autosave_Chasing_A_Dream_20230930T091520_Bug.vsgm1/file

**Comment by Nordsoft91** [comment] 2023-09-30 12:40
Did hero pass through garrison prior exchange with other hero?

**Comment by LordIofIThunder** [comment] 2023-09-30 12:41
> Did hero pass through garrison prior exchange with other hero?

No.

**Comment by Nordsoft91** [comment] 2023-09-30 12:42
And please specify version and mods used

**Comment by LordIofIThunder** [comment] 2023-09-30 12:52
> And please specify version and mods used
Device:Poco x3 pro
Vcmi version:1.4
Mods:
1-retreat town
2-asphalt terrain
3-asylum town
4-boost AI 0.2
5-campaign heroes 1.14
6-cathedral twon
7-courtyard town
8-death valley 1.36
9-elemental nodes 1.0.1
10-english translation
11-fairy town
12-grove town
13-haven 1.21
14-heavenly forge 2000 2.2
15-Hogh-res menu
16-Horn of the abyss 1.6.12
17-new adventure map spells 0.1
18-pavilion town 2.9.0
19-preserve town 1.1.9
20-retreat 0.5.6
21-reworked commanders 1.2
22-warzyw-templates 1.05

**Comment by by003** [comment] 2023-10-03 01:53
I reckon it belongs to hero repeat bug. Sometimes a moving hero is repeat with a prison hero and vice versa. If you release a prison hero and he or she is repeat with other's moving hero, this situation happens as well.

**Comment by krs0** [comment] 2023-10-03 09:08
In the past something similar appeared because of 2 Orin heroes on map

**Comment by SoundSSGood** [comment] 2023-11-01 13:15
Possible related to https://github.com/vcmi/vcmi/issues/3094

**Comment by IvanSavenko** [comment] 2023-11-19 21:02
Closing, duplicate of #2299

**Closed by IvanSavenko** 2023-11-19 21:02 UTC
Labels: bug
