### ISSUE TITLE
Crash on AI turn

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3761] opened 2024-04-13 05:06 UTC
'VCMI 1.5.0.53fcd3ad26ff7ec7f3462e5bfb51dd0252074956'
I don't know what happened. Game  just has been crashed. After press end of turn. (Blue bot). The map does not show what the enemy hero was doing at that time.

> [2024-Apr-13 08:00:37.958362] DEBUG [AIGateway::makeTurn] ai - Can not allocate special transition node while moving (207 34 1) -> (207 35 1)
> [2024-Apr-13 08:00:55.034361] ERROR [dcc] global - Disaster happened.
> [2024-Apr-13 08:00:55.034361] ERROR [AIGateway::makeTurn] global - Disaster happened.
> [2024-Apr-13 08:00:55.034361] ERROR [1488] global - Disaster happened.
> [2024-Apr-13 08:00:55.035361] ERROR [dcc] global - Reason: 0xc0000005 - EXCEPTION_ACCESS_VIOLATION at 0033:0,000,7FF,A5D,DCD,850
> [2024-Apr-13 08:00:55.035361] ERROR [AIGateway::makeTurn] global - Reason: 0xc0000005 - EXCEPTION_ACCESS_VIOLATION at 0033:0,000,7FF,A5D,DCD,850
> [2024-Apr-13 08:00:55.034361] ERROR [5b8] global - Disaster happened.
> [2024-Apr-13 08:00:55.035361] ERROR [1488] global - Reason: 0xc0000005 - EXCEPTION_ACCESS_VIOLATION at 0033:0,000,7FF,A5D,DCD,850
> [2024-Apr-13 08:00:55.037361] ERROR [AIGateway::makeTurn] global - Attempt to read from 0x0,000,000,000,000,010
> [2024-Apr-13 08:00:55.037361] ERROR [dcc] global - Attempt to read from 0x0,000,000,000,000,010
> [2024-Apr-13 08:00:55.037361] ERROR [1488] global - Attempt to read from 0x0,000,000,000,000,010
> [2024-Apr-13 08:00:55.037361] ERROR [5b8] global - Reason: 0xc0000005 - EXCEPTION_ACCESS_VIOLATION at 0033:0,000,7FF,A5D,DCD,850
> [2024-Apr-13 08:00:55.038361] ERROR [AIGateway::makeTurn] global - Thread ID: 6296
> [2024-Apr-13 08:00:55.038361] ERROR [5b8] global - Attempt to read from 0x0,000,000,000,000,010
> [2024-Apr-13 08:00:55.038361] ERROR [dcc] global - Thread ID: 3532
> [2024-Apr-13 08:00:55.038361] ERROR [1488] global - Thread ID: 5256
> [2024-Apr-13 08:00:55.040361] ERROR [5b8] global - Thread ID: 1464
> [2024-Apr-13 08:00:55.246360] ERROR [AIGateway::makeTurn] global - Crash info will be put in VCMI_client.exe_crashinfo.dmp
> [2024-Apr-13 08:00:55.246360] ERROR [dcc] global - Crash info will be put in VCMI_client.exe_crashinfo.dmp
> [2024-Apr-13 08:00:55.246360] ERROR [5b8] global - Crash info will be put in VCMI_client.exe_crashinfo.dmp
> [2024-Apr-13 08:00:55.247361] ERROR [1488] global - Crash info will be put in VCMI_client.exe_crashinfo.dmp

[1.zip](https://github.com/vcmi/vcmi/files/14965341/1.zip)
[Element Land.zip](https://github.com/vcmi/vcmi/files/14965345/Element.Land.zip)

**Comment by IvanSavenko** [comment] 2024-04-18 13:51
Unable to reproduce either...

**Comment by Povelitelh3** [comment] 2024-04-19 06:01
> Unable to reproduce either...

dump is here https://drive.google.com/file/d/1Anx-y2_hLzbiDWPptyLOcS3ytnjV0f1X/view?usp=drive_link

**Comment by IvanSavenko** [comment] 2024-04-19 09:33
Which build ID was used for that dump?
Latest develop fails to open it. Build from issue description (53fcd3ad26ff7ec7f3462e5bfb51dd0252074956) does not works either.

**Comment by Povelitelh3** [comment] 2024-04-19 09:59
> Which build ID was used for that dump? Latest develop fails to open it. Build from issue description ([53fcd3a](https://github.com/vcmi/vcmi/commit/53fcd3ad26ff7ec7f3462e5bfb51dd0252074956)) does not works either.

it was 1.5.0.9390825ee7b44d38f3628118d1798bbe74183826

**Comment by IvanSavenko** [comment] 2024-04-19 10:22
Crash in NKAI, in object graphs.
Not 100% sure what's wrong, possibly thread races.
@nullkiller can you take a look when you have a moment?
```
[Inline Frame] Nullkiller.dll!int3::operator==(const int3 &) Line 82	C++
[Inline Frame] Nullkiller.dll!std::equal_to<int3>::operator()(const int3 &) Line 393	C++
[Inline Frame] Nullkiller.dll!std::_Uhash_compare<int3,std::hash<int3>,std::equal_to<int3>>::operator()(const int3 &) Line 152	C++
[Inline Frame] Nullkiller.dll!std::_Hash<std::_Umap_traits<int3,NKAI::ObjectNode,std::_Uhash_compare<int3,std::hash<int3>,std::equal_to<int3>>,std::allocator<std::pair<int3 const ,NKAI::ObjectNode>>,0>>::_Find_last(const int3 &) Line 1574	C++
[Inline Frame] Nullkiller.dll!std::_Hash<std::_Umap_traits<int3,NKAI::ObjectNode,std::_Uhash_compare<int3,std::hash<int3>,std::equal_to<int3>>,std::allocator<std::pair<int3 const ,NKAI::ObjectNode>>,0>>::_Find(const int3 &) Line 1213	C++
[Inline Frame] Nullkiller.dll!std::_Hash<std::_Umap_traits<int3,NKAI::ObjectNode,std::_Uhash_compare<int3,std::hash<int3>,std::equal_to<int3>>,std::allocator<std::pair<int3 const ,NKAI::ObjectNode>>,0>>::find(const int3 &) Line 1230	C++
Nullkiller.dll!vstd::contains<NKAI::ObjectNode,int3,int3>(const std::unordered_map<int3,NKAI::ObjectNode,std::hash<int3>,std::equal_to<int3>,std::allocator<std::pair<int3 const ,NKAI::ObjectNode>>> & c, const int3 & i) Line 312	C++
[Inline Frame] Nullkiller.dll!NKAI::ObjectGraph::hasNodeAt(const int3 &) Line 111	C++
[Inline Frame] Nullkiller.dll!NKAI::ObjectGraphCalculator::addMinimalDistanceJunctions::__l2::<lambda_e140a4600fad45edb97aaa745380bcea>::operator()(const int3 &) Line 117	C++
Nullkiller.dll!NKAI::pforeachTilePaths::__l4::<lambda>(const tbb::detail::d1::blocked_range<unsigned __int64> & r) Line 43	C++
[Inline Frame] Nullkiller.dll!tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned __int64>,void <lambda>(const tbb::detail::d1::blocked_range<unsigned __int64> &),tbb::detail::d1::auto_partitioner const>::run_body(tbb::detail::d1::blocked_range<unsigned __int64> &) Line 119	C++
Nullkiller.dll!tbb::detail::d1::dynamic_grainsize_mode<tbb::detail::d1::adaptive_mode<tbb::detail::d1::auto_partition_type>>::work_balance<tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned __int64>,void <lambda>(const tbb::detail::d1::blocked_range<unsigned __int64> &),tbb::detail::d1::auto_partitioner const>,tbb::detail::d1::blocked_range<unsigned __int64>>(tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned __int64>,void <lambda>(const tbb::detail::d1::blocked_range<unsigned __int64> &),tbb::detail::d1::auto_partitioner const> & start, tbb::detail::d1::blocked_range<unsigned __int64> & range, tbb::detail::d1::execution_data & ed) Line 466	C++
[Inline Frame] Nullkiller.dll!tbb::detail::d1::partition_type_base<tbb::detail::d1::auto_partition_type>::execute(tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned __int64>,void <lambda>(const tbb::detail::d1::blocked_range<unsigned __int64> &),tbb::detail::d1::auto_partitioner const> &) Line 288	C++
Nullkiller.dll!tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned __int64>,void <lambda>(const tbb::detail::d1::blocked_range<unsigned __int64> &),tbb::detail::d1::auto_partitioner const>::execute(tbb::detail::d1::execution_data & ed) Line 173	C++

```

**Comment by nullkiller** [comment] 2024-04-21 09:05
Should be addressed in my latest PR

**Closed** 2024-04-21 11:00 UTC
Labels: bug
