### ISSUE TITLE
Shadow of Death campaign not working correctly

### ISSUE THREAD

**Issue by GaryKleppe** [vcmi/vcmi#3307] opened 2023-12-12 02:29 UTC
**Describe the bug**
I ran the "Birth of a Barbarian" campaign after the latest update and noticed three issues.

1) At the start of the third scenario, Yog should have the Angelic Alliance, since the goal for this scenario is to deliver parts of it. He doesn't. At the start of the last two scenario he should have four and two of the artifacts respectively, for the same reason. This would make the scenario unwinnable, except...

2) When you defeat all the enemies, the scenario automatically ends. This shouldn't happen for scenarios where there's a quest to accomplish, like all of the ones in this campaign. I ran the first scenario of Gem's campaign to double-check this and the same thing happened there.

3) In various places, it's showing what are obviously text lookup keys rather than the text that should be looked up from them. For example, if you click on "Scenario Information" it says "campaign.yog.name" rather than "Birth of a Barbarian".

**Game logs**
Please attach game logs: `VCMI_client.txt`, `VCMI_server.txt` etc.
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/13642757/VCMI_Server_log.txt)
[VCMI_Client_log.zip](https://github.com/vcmi/vcmi/files/13642954/VCMI_Client_log.zip)

**To Reproduce**
1. Run the "A Tough Start" scenario in the "Birth of a Barbarian Campaign"
2. Note that Yog does not have the artifacts that he's supposed to deliver.
3. Check the "Scenario Information" and notice that it says "campaign.yog.name" and "campaign.yog.description" in the header.
4. Play the scenario. Take over the enemy towns and defeat all of the heroes but don't do any of the quests. It will complete the scenario.
5. Repeat for the remaining two scenarios in the campaign.

**Expected behavior**
Yog should begin "A Tough Start" carrying the Angelic Alliance. He should begin the next two scenarios carrying those parts of the Alliance that he has not yet delivered. The player should not be able to complete the scenario without accomplishing the quests. All text lookups should show the looked-up text and not the keys.

**Actual behavior**
Yog starts the last three of his scenarios without the artifacts that he should have. Defeating the enemy troops ends the scenario even though I didn't complete the quests. Text lookup keys are showing.

**Did it work earlier?**
I had not run the Yog campaign in VCMI prior to this so can't say whether the first issue was working. The second was working correctly for the other Shadow of Death campaigns prior to the latest update. I think the third was as well.

**Screenshots**

**Version**
 - OS: Ubuntu Linux
 - Version: 1.4.0

**Additional context**

**Comment by IvanSavenko** [comment] 2023-12-12 11:08
Hi. Unfortunately unable to reproduce this part:

> In various places, it's showing what are obviously text lookup keys rather than the text that should be looked up from them. For example, if you click on "Scenario Information" it says "campaign.yog.name" rather than "Birth of a Barbarian".

Starting 1st scenario of "Birth of Barbarian" shows correct text in scenario information menu.

You are not the first one to report it, so bug likely does exists, but still looking for a way to reproduce it.

**Comment by GaryKleppe** [comment] 2023-12-13 23:36
I noticed another difference with the Yog campaign. In regular Heroes 3 "Birth of a Barbarian," Yog has no spell book and is not allowed to buy one; if he tries, it says something about how he's forsaken magic in all of its forms. The good news is that even though he's a Wizard, all of his level-ups seem to go into either Offense or Defense and not Knowledge or Spell Power. In the VCMI version of this campaign, Yog doesn't start with a spell book but can buy one, and his level-up boosts can go to any of the four stats.

**Comment by IvanSavenko** [comment] 2024-01-31 09:22
> 1) At the start of the third scenario, Yog should have the Angelic Alliance, since the goal for this scenario is to deliver parts of it. He doesn't. At the start of the last two scenario he should have four and two of the artifacts respectively, for the same reason. This would make the scenario unwinnable, except...

Will be fixed in 1.5

> 2) When you defeat all the enemies, the scenario automatically ends. This shouldn't happen for scenarios where there's a quest to accomplish, like all of the ones in this campaign. I ran the first scenario of Gem's campaign to double-check this and the same thing happened there.

Yog campaign: will fix.
Gem campaign: unable to reproduce. First scenario does not have any quests to complete, second scenario has quest but defeating all enemies does not ends scenario until you've completed the quest.

> 3) In various places, it's showing what are obviously text lookup keys rather than the text that should be looked up from them. For example, if you click on "Scenario Information" it says "campaign.yog.name" rather than "Birth of a Barbarian".

Mostly fixed in 1.4, however it looks like one case is still missing. Will fix.

**Closed** 2024-02-01 09:30 UTC
Labels: bug, h3feature, campaigns
