### ISSUE TITLE
Stack of summoned Demons turns back to the original stack

### ISSUE THREAD

**Issue by boctavian96** [vcmi/vcmi#3659] opened 2024-03-12 17:04 UTC
**Describe the bug**
After the battle a summoned Demon stack will return to the original stack.

**Game logs**
Unfortunately the files are too big. If it's needed I can send them via other service.

**To Reproduce**
1. Go on battle with a stack of Pit Lords and other creatures.
2. When a stack of yours is destroyed use the Pit Lords 'Summon Demons' ability.
3. The demons will be summoned. 
4. After the battle the summoned demons will return to their original stack. In my case I've lost 100 Gogs and summoned around 40 Demons, after the battle was over the 40 Demons turned to 100 Gogs.

**Expected behavior**
After the battle I expect to have the Demons summoned by the Pit Lords.

**Actual behavior**
The Demons stack turns back to the original stack that was destroyed in the battle.

**Did it work earlier?**
No idea.

**Screenshots**
NA

**Version**
 - OS: Mac OS M1
 - Version: VCMI 1.4.5

**Off-Topic**
I'd be interested in trying to solve this on my own. Can someone please give me some tips? On what classes should I check?

**Comment by IvanSavenko** [comment] 2024-03-12 17:22
Sounds like duplicate of https://github.com/vcmi/vcmi/issues/3221
So should be already fixed in 1.5

**Comment by kambala-decapitator** [comment] 2024-03-12 18:39
> Unfortunately the files are too big. If it's needed I can send them via other service.

FYI you can zip / 7z / tarxz them

**Comment by boctavian96** [comment] 2024-03-12 20:56
> Sounds like duplicate of https://github.com/vcmi/vcmi/issues/3221
> So should be already fixed in 1.5

Hello Ivan, yes it's the same issue. 
I didn't found it when I created the issue. 

I'm sorry 😞 for duplicating it

**Closed** 2024-03-13 10:16 UTC
Labels: bug
