### ISSUE TITLE
Hero moves in a saccadic way on adventure map at client side

### ISSUE THREAD

**Issue by oldfoz** [vcmi/vcmi#3565] opened 2024-01-26 15:17 UTC
I have just downloaded v1.4.5 and tried multiplayer mode for the first time.
Two assets, Dell Precision 7530 on Windows 10, and iPad mini 5.

First case, start multiplayer game with simultaneous turns
at laptop as server and iPad as client in home 300 Mbps local network through Wi-Fi.
All is working, but moves of hero on the map, and construction process of buildings in town
are not smooth, they are sharp and extremely saccadic for iPad (client),
for laptop (sever) no such issues are detected.

Second case, I use laptop as client, and iPad as server,
and observe reverse situation, for iPad (server) not issues,
for laptop (client) -- saccadic moves we have. 

Any ideas how this issue could be fixed?
I attached logs from the laptop.
[server_log.txt](https://github.com/vcmi/vcmi/files/14066455/server_log.txt)
[VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/14066454/VCMI_Server_log.txt) 
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/14066435/VCMI_Client_log.txt)

**Comment by IvanSavenko** [comment] 2024-01-26 15:21
Known:
 - #1133 

Will try to fix at least most noticeable cases, e.g. hero movement for 1.5

**Comment by oldfoz** [comment] 2024-01-26 15:22
> Known:
> 
> * [Hero movement is very slow when playing online #1133](https://github.com/vcmi/vcmi/issues/1133)
> 
> Will try to fix at least most noticeable cases, e.g. hero movement for 1.5

Nice to hear, thank you

**Comment by IvanSavenko** [comment] 2024-02-05 20:43
Closing as duplicate of #1133

**Closed by IvanSavenko** 2024-02-05 20:43 UTC
Labels: bug
