### ISSUE TITLE
Crash in combat replays 

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#4030] opened 2024-05-22 10:52 UTC
**Describe the bug**
If forget to click unlimited combat replays option before entering the new map (even it is already chosen last time), the game will crash if using a restart battle. 

**To Reproduce**
1. Go to any map without click unlimited combat replays option,
2. Enter a battle, click escape, then click left button to restart this battle
3. See error

**Expected behavior**
The game will remember the option to restart battle.

**Actual behavior**
Game crashes. Even the option is chosen last time.
![image](https://github.com/vcmi/vcmi/assets/127420617/d2766211-49c2-4de0-8c27-cb51cc97bf98)

**Version**
 - OS: Windows
 - Version: 1.5.1

**Comment by IvanSavenko** [comment] 2024-05-22 12:38
Unable to reproduce:
- started map, 'unlimited battle replay' option is disabled, 
- started battle
- clicked escape from battle, confirm
- on battle result window I don't have option to replay battle

**Comment by by003** [comment] 2024-05-22 12:54
It is easy:
1. active 'unlimited battle replay'
2. quit the game
3. enter the game again
4. go to any map and attack any neutral creatures
5. retreat and replay

**Comment by IvanSavenko** [comment] 2024-05-22 14:52
still unable to reproduce for some reason.
Tried both with quick combat and without quick combat.

Can you upload log with crash?

**Comment by by003** [comment] 2024-05-22 15:06
It crashes immediately with no error windows. 
Could you tell me whether it caused by some compatiblity problems? Which branch is more stable?

I tried WindowsAlternative version.

**Comment by IvanSavenko** [comment] 2024-05-22 18:47
> It crashes immediately with no error windows. Could you tell me whether it caused by some compatiblity problems? 

No idea. Right now I have no information about this crash.
No log, no save file, no crash dump, nothing.

> Which branch is more stable?

1.5.1 release should be the most stable. 
Beta branch should also be stable, but not tested as much as 1.5.1.
Develop is least tested branch at the moment.

> I tried WindowsAlternative version.

Do you have VCMI_Client_crashdump.dmp file in game install directory? If yes - can you upload it?

**Comment by IvanSavenko** [comment] 2024-05-23 12:23
Got log with same crash from another player on Discord. Will be fixed in 1.5.2

**Comment by by003** [comment] 2024-05-27 13:03
Can I ask for when will 1.5.2 release? Hard to play with this situation...

**Closed** 2024-05-28 20:50 UTC
Labels: bug
