### ISSUE TITLE
Siege battle not starting. Towers do not shoot.

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1955] opened 2023-04-12 17:19 UTC
**Describe the bug**
In a specific map siege battle is not starting. Only autocombat works.
Simple test map with a castle fully built.

@Nordsoft91 Seems to be from tactics hero!

**To Reproduce**
Open Test map
Attack Rampart castle

https://user-images.githubusercontent.com/15194321/231538333-c5faa7f6-f34a-4ed4-8997-010ff28e7fe9.mp4

**Version**
[A Capitol Test.zip](https://github.com/vcmi/vcmi/files/11214213/A.Capitol.Test.zip)

 - OS: Windows
 - Version: develop

**Comment by rilian-la-te** [comment] 2023-04-12 17:30
@krs, just tested on linux on #1932 - all is working.

**Comment by krs0** [comment] 2023-04-12 17:33
with a hero without tactics it works!

**Comment by rilian-la-te** [comment] 2023-04-12 17:34
@krs I tried with tactics, it also works.

**Comment by rilian-la-te** [comment] 2023-04-12 17:38
@krs0 reproduced with Isra on All for One map.

**Comment by IvanSavenko** [comment] 2023-07-13 10:21
Still relevant? Or has been fixed?

**Comment by rilian-la-te** [comment] 2023-07-13 10:33
I think I fixed it already.

**Comment by rilian-la-te** [comment] 2023-07-13 10:33
but need futher testing.

**Comment by IvanSavenko** [comment] 2023-07-15 18:21
Seems to be fixed now

**Closed by IvanSavenko** 2023-07-15 18:21 UTC
Labels: bug
