### ISSUE TITLE
After playing for a longer period of time the game crashes on loading a map

### ISSUE THREAD

**Issue by HarkUhm** [vcmi/vcmi#2900] opened 2023-09-22 15:04 UTC
**Describe the bug**
When I am playing for a 30-60 minutes and I am very quickly cliking on a saved game to load it on a loading screen, sometimes the "load" button remains in a state "not clicked" and if I will click it once, or click once again on a saved game, the game will crash.

**Version**
 - OS: [Windows 10]
 - Version: [VCMI 1.3.2]

**Comment by Nordsoft91** [comment] 2023-09-22 23:22
eventually will be fixed with https://github.com/vcmi/vcmi/pull/2889

**Comment by dydzio0614** [comment] 2023-09-22 23:31
yes or no, the issue is related to loading game tens of times over longer session, there may be some memory leak or whatever going on

**Comment by Nordsoft91** [comment] 2023-09-23 00:37
> sometimes the "load" button remains in a state "not clicked" and if I will click it once, or click once again on a saved game, the game will crash.

This scenario

**Comment by HarkUhm** [comment] 2023-09-23 16:22
Ok, I have aquired something similar after about 20 loadings, this time game didn't crashed to windows, but also showed error, stopped loading and button remained clicked:
![ghgh](https://github.com/vcmi/vcmi/assets/141812373/5d411708-55a0-4636-ae3e-6909d272d92a)
This is log?:
https://www.dropbox.com/s/86k6px7rrps4ynw/VCMI_client.exe_crashinfo.dmp?dl=0

**Closed** 2023-09-26 17:29 UTC
Labels: bug, client

**Comment by Nordsoft91** [comment] 2023-09-26 17:30
@HarkUhm , can you please test using either this build https://github.com/vcmi/vcmi/actions/runs/6313616436 or using nightly build which will appear tomorrow?
