### ISSUE TITLE
The game resolution scale has 140% limite, which is too small for 6.5" android phone, I can't set higher than 140%. And label error.

### ISSUE THREAD

**Issue by Rextair** [vcmi/vcmi#3196] opened 2023-11-17 21:24 UTC
Hello, I would like to send some issues about vcmi on android. 

I was really happy that vcmi is finally playable on android with improvements like touchscreen navigation and a circle of faster action like a split army by one, for example. Finally, my long waited feature is widescreen support. 

But I have got an issue experiencing a game resolution scale. It's has a limite 140%! I can't make it more 200%, so experiencing a game would be much easier! I really want to scale the game up to 200% or even higher.

The phone I have is 6,5" with resolution 2400x1080. I have attached an image example of what it looks like from my view.

Also, I have got a weird issue with the game labels in the pause menu. After I installed WOG mode trought launcher, labels in pause menu, enemies on map description same with artifacts on the map having weird labels, like a code.

Even after I deleted WOG mod, these labels were still shown. 

I have also attached some screenshot demonstrations of this issue.

**Screenshots**
![IMG_20231117_223722_512.jpg](https://github.com/vcmi/vcmi/assets/59028081/637422f7-90a4-49f6-81c2-8734ec698ec7)

![IMG_20231117_223722_746.jpg](https://github.com/vcmi/vcmi/assets/59028081/2363ab8d-5f9b-43c4-95c0-165936542d60)

![Screenshot_20231117_231942_VCMI.jpg](https://github.com/vcmi/vcmi/assets/59028081/0ec2df47-b555-4570-805f-5e42f6555d23)

![Screenshot_20231117_232042_VCMI.jpg](https://github.com/vcmi/vcmi/assets/59028081/49925442-9c0c-4d2e-b122-3d9febeab82c)

**Version**
 - OS: Android
 - Version: 1.3.2

**Comment by IvanSavenko** [comment] 2023-11-17 21:42
Hi. To fix labels, you need to delete this directory:
`Android\data\is.xyz.vcmi\files\vcmi-data\Mods\vcmi`
(on recent Android's this directory is only accessible from PC via USB)

As for resolution scale - unfortunately this is maximum that we support right now.
Increasing it further will result in town / battle screen getting cut off since they no longer fit the screen.
We do have some features to improve gameplay on small screen - adventure map zoom, targeting selection in battle, etc. Check video here: https://github.com/vcmi/vcmi/pull/3191

Are there any particular places that you find to not be comfortable to use with touchscreen? Even on my old 5-inch phone game was reasonably playable, and on new 6.1-inch phone the only issue I found is selection of starting hero/town (will be improved in next release)

**Comment by Rextair** [comment] 2023-11-18 12:43
Thanks, labels are fixed. Well, if that's so, I can suggest adding some shortcuts like a button or a combination that will call a fast-circle select or as calling radial menu. Or even you can add gamepad support! It would be an amazing way to play Heroes 3, for me. I made some concepts back in August this year. You can take a look.

![Heroes3GamepadButtons](https://github.com/vcmi/vcmi/assets/59028081/d5f6861e-a569-4140-b4fc-16e6acd70da0)
![image](https://github.com/vcmi/vcmi/assets/59028081/1724e1e1-9189-41a2-93b7-8a6fac1df64f)

**Comment by IvanSavenko** [comment] 2023-11-18 12:55
> Maybe add a screen resolution like, like 800x600 and scale the game to be widescreen

This is exactly what maximum resolution scale does. If resolution scale maxed out then game will use 800x600 resolution internally and then upscale it to your screen (well, it is actually something like 1066x600 in case of 16x9 widescreen, but idea is the same)

> Or just make everything bigger except the town UI. 

How? If we make adventure map bigger it won't fit the screen. We'll need to actually remove some UI elements for that.
Same goes to town screen, battle screen and actually most of UI windows - exchange window, hero window, puzzle map window, etc. Most of Heroes 3 UI is almost 600px in height

> Or even you can add gamepad support!

Not a bad idea, if/when we find time for that - our team is quite small, so we have to prioritize. However it won't help much with gameplay on mobile devices.

**Comment by IvanSavenko** [comment] 2024-11-26 15:23
Labels - fixed on player side
Maximal resolution scaling - works as designed
Gamepad support added in 1.5

**Closed by IvanSavenko** 2024-11-26 15:23 UTC
Labels: bug
