### ISSUE TITLE
[Android]Failed to use Cure spell, prompt "Unknown problem with this spell no more information available"

### ISSUE THREAD

**Issue by tianmaster** [vcmi/vcmi#1869] opened 2023-04-04 03:02 UTC
Describe the bug
Android, new est daily builds (VCMI brand development e1c3550), Cure spell, Resurrection spell, and all similar spells fail. First Aid Tent cannot work

Game logs
Not applicable

To Reproduce

Using Cure spell，or using Firstaidtent

Actual behavior
Using Cure spell fail.
It prompts"Unknown problem with this spell no more information available"
First Aid Tent will be skipped.

Did it work earlier?
VCMI brand development 6c693f2 and previous versions can work properly

Screenshots
![Error_Cure](https://user-images.githubusercontent.com/51704354/229676137-c045ef6f-a963-4c44-9916-c54e6ea52c30.jpg)

Version

OS: Android MIUI 14.0.3
Version: VCMI-branch-develop-e1c3550
Additional context

**Comment by rilian-la-te** [comment] 2023-04-04 08:55
I tried to use Cure on Linux on #1822, I can cast Cure and Resurrection on Centaurs. @nullkiller how heal spell effect can be broken on Android?

**Comment by tianmaster** [comment] 2023-04-04 09:03
> 

On Windows, I tried it with the latest version of Daily Build. It works fine. I'm weird

**Comment by tianmaster** [comment] 2023-04-04 09:04
> 我尝试在 #1822 上的 Linux 上使用 Cure，我可以在 Centaurs 上施放 Cure 和复活。@nullkiller如何在安卓设备上破解治疗法术效果？

On Windows, I tried it with the latest version of Daily Build. It works fine. I'm weird

**Comment by kambala-decapitator** [comment] 2023-04-05 13:13
can reproduce on android with the latest beta build.
[logs.zip](https://github.com/vcmi/vcmi/files/11159095/logs.zip)

**Comment by IvanSavenko** [comment] 2023-04-05 13:33
> can reproduce on android with the latest beta build, checked on Cure spell. [logs.zip](https://github.com/vcmi/vcmi/files/11159095/logs.zip)

Not sure what's going on. From logs it looks like `mySpell->canBeCast` call returned false but have not set any proper 'problem' (error message). Don't see any way for this to happen...
https://github.com/vcmi/vcmi/blob/develop/client/windows/CSpellWindow.cpp#L537

**Comment by rilian-la-te** [comment] 2023-04-05 14:35
@IvanSavenko it is possible, than we do not correctly set what effect is smart? Is this bug reproducible on single app build on desktop? I can try to build single app Linux and reproduce this bug.

**Comment by rilian-la-te** [comment] 2023-04-05 14:36
@IvanSavenko WTF in server log?

```
[2023-Apr-05 15:51:54.252993] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253066] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253093] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253121] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253162] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253192] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253220] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253262] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253296] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253342] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253373] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253416] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253460] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253500] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253530] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253586] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:54.253617] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.253655] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.253682] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.253711] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.253900] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.253946] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.253977] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254009] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254083] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254112] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254138] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254168] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254196] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:54.254235] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254264] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254294] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254323] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254353] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254382] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254410] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254437] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254477] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254508] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254537] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254567] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254597] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254627] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254657] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.254684] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254719] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254750] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254779] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254809] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.254846] ERROR global - Unknown effect type 'core:sacrifice'
[2023-Apr-05 15:51:54.254877] ERROR global - Unknown effect type 'core:sacrifice'
[2023-Apr-05 15:51:54.254907] ERROR global - Unknown effect type 'core:sacrifice'
[2023-Apr-05 15:51:54.254938] ERROR global - Unknown effect type 'core:sacrifice'
[2023-Apr-05 15:51:54.255137] ERROR global - Unknown effect type 'core:teleport'
[2023-Apr-05 15:51:54.255168] ERROR global - Unknown effect type 'core:teleport'
[2023-Apr-05 15:51:54.255196] ERROR global - Unknown effect type 'core:teleport'
[2023-Apr-05 15:51:54.255224] ERROR global - Unknown effect type 'core:teleport'
[2023-Apr-05 15:51:54.255257] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:54.255288] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:54.255319] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:54.255348] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:54.255383] ERROR global - Unknown effect type 'core:clone'
[2023-Apr-05 15:51:54.255412] ERROR global - Unknown effect type 'core:clone'
[2023-Apr-05 15:51:54.255441] ERROR global - Unknown effect type 'core:clone'
[2023-Apr-05 15:51:54.255469] ERROR global - Unknown effect type 'core:clone'
[2023-Apr-05 15:51:54.255503] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255548] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255578] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255621] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255657] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255698] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255731] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255770] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255806] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255842] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255907] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255939] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255966] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.255990] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.256031] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.256058] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:54.256189] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.256224] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.256251] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.256281] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:54.256394] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.256428] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.256454] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.256481] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.256524] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.256555] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.256590] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.256620] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:54.256660] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.256700] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.256727] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.256770] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:54.256813] ERROR global - Unknown effect type 'core:demonSummon'
[2023-Apr-05 15:51:54.256847] ERROR global - Unknown effect type 'core:demonSummon'
[2023-Apr-05 15:51:54.256872] ERROR global - Unknown effect type 'core:demonSummon'
[2023-Apr-05 15:51:54.256899] ERROR global - Unknown effect type 'core:demonSummon'
```

**Comment by rilian-la-te** [comment] 2023-04-05 14:37
@IvanSavenko in client log too

```
[2023-Apr-05 15:51:50.509260] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509316] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509340] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509365] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509407] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509529] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509586] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509615] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509646] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509675] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509752] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509795] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509860] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509894] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509925] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509964] ERROR global - Unknown effect type 'core:obstacle'
[2023-Apr-05 15:51:50.509996] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.510046] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.510075] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.510101] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.510298] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510354] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510388] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510421] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510461] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510489] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510517] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510541] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510564] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:50.510597] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510624] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.510650] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510677] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.510702] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510728] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.510755] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510783] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.510821] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510848] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.510875] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510902] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.510928] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.510953] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.510979] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.511004] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.511037] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.511066] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.511094] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.511122] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.511166] ERROR global - Unknown effect type 'core:sacrifice'
[2023-Apr-05 15:51:50.511192] ERROR global - Unknown effect type 'core:sacrifice'
[2023-Apr-05 15:51:50.511218] ERROR global - Unknown effect type 'core:sacrifice'
[2023-Apr-05 15:51:50.511244] ERROR global - Unknown effect type 'core:sacrifice'
[2023-Apr-05 15:51:50.511420] ERROR global - Unknown effect type 'core:teleport'
[2023-Apr-05 15:51:50.511449] ERROR global - Unknown effect type 'core:teleport'
[2023-Apr-05 15:51:50.511475] ERROR global - Unknown effect type 'core:teleport'
[2023-Apr-05 15:51:50.511500] ERROR global - Unknown effect type 'core:teleport'
[2023-Apr-05 15:51:50.511532] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:50.511562] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:50.511591] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:50.511618] ERROR global - Unknown effect type 'core:removeObstacle'
[2023-Apr-05 15:51:50.511653] ERROR global - Unknown effect type 'core:clone'
[2023-Apr-05 15:51:50.511717] ERROR global - Unknown effect type 'core:clone'
[2023-Apr-05 15:51:50.511742] ERROR global - Unknown effect type 'core:clone'
[2023-Apr-05 15:51:50.511764] ERROR global - Unknown effect type 'core:clone'
[2023-Apr-05 15:51:50.511794] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.511822] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.511848] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.511874] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.511906] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.511933] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.511960] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.511988] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.512022] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.512048] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.512075] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.512100] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.512132] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.512159] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.512186] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.512214] ERROR global - Unknown effect type 'core:summon'
[2023-Apr-05 15:51:50.512335] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.512372] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.512398] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.512420] ERROR global - Unknown effect type 'core:dispel'
[2023-Apr-05 15:51:50.512516] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.512550] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.512576] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.512601] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.512630] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.512661] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.512689] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.512716] ERROR global - Unknown effect type 'core:catapult'
[2023-Apr-05 15:51:50.512754] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.512796] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.512822] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.512851] ERROR global - Unknown effect type 'core:heal'
[2023-Apr-05 15:51:50.512900] ERROR global - Unknown effect type 'core:demonSummon'
[2023-Apr-05 15:51:50.512939] ERROR global - Unknown effect type 'core:demonSummon'
[2023-Apr-05 15:51:50.512968] ERROR global - Unknown effect type 'core:demonSummon'
[2023-Apr-05 15:51:50.513008] ERROR global - Unknown effect type 'core:demonSummon'
```
Maybe this bug is something related to effect loading?

**Comment by IvanSavenko** [comment] 2023-04-05 14:56
Definitely WTF.

Constructor for RegisterEffect classes is not called? Compiler optimized away "unused" variables?
Effects GlobalRegistry for some reason got several instances?
Something specific to Android? 
Some other initialization order shenanigans? (WHY spell effect have registration at static initialization stage, just why?...)

I guess one option would be to get rid of this GlobalRegistry idiocity & initialize all effects someplace else, e.g. in CSpellHandler constructor.

**Comment by rilian-la-te** [comment] 2023-04-05 15:01
@IvanSavenko I think this is not Global Registry bug, most likely someone forgot to init VCMI_LIB_NAMESPACE somewhere. Interesting, can we get this bug on single app build on desktop or not.

**Comment by rilian-la-te** [comment] 2023-04-05 15:03
@IvanSavenko effect in CSpellHandler - bad. I think we should have CEffectHandler specially for effects, effects is useful even outside of spellcasting.

**Comment by kambala-decapitator** [comment] 2023-04-05 15:04
> Interesting, can we get this bug on single app build on desktop or not.

I'll check on iOS

**Comment by rilian-la-te** [comment] 2023-04-05 15:05
@kambala-decapitator maybe on Mac?

**Comment by kambala-decapitator** [comment] 2023-04-05 15:38
can't reproduce the same on iOS, but there's a different issue: tried to heal Golem (where the cursor is), got this

![Screen Shot 2023-04-05 at 18 34 22](https://user-images.githubusercontent.com/1557784/230131533-4f9d065b-9186-4ce3-aa89-2f03b39e81d2.png)

[logs.zip](https://github.com/vcmi/vcmi/files/11160543/logs.zip)


> @kambala-decapitator maybe on Mac?

can try building later

**Comment by rilian-la-te** [comment] 2023-04-05 15:40
@kambala-decapitator beta or develop?

**Comment by kambala-decapitator** [comment] 2023-04-05 15:47
latest beta (just like android), you can also see the version in the logs

**Comment by rilian-la-te** [comment] 2023-04-05 15:48
@kambala-decapitator will try to reproduce on develop. If golem bug is fixed there - then it is good. How First Aid Tent reacts on gargoyles, black dragons and other creatures?

**Comment by kambala-decapitator** [comment] 2023-04-05 17:16
macOS single app: same issue as on iOS, tried to cure Imps

**Comment by rilian-la-te** [comment] 2023-04-05 17:17
Strange log entries?

**Comment by kambala-decapitator** [comment] 2023-04-05 17:19
> Strange log entries?

yes, and the unit isn't actually healed (also no spell animation)

**Comment by rilian-la-te** [comment] 2023-04-05 17:21
Because effects is not loaded somehow. Other spells like fire wall?

**Comment by kambala-decapitator** [comment] 2023-04-05 17:30
tested some spells, only Cure didn't seem to work

https://youtu.be/XBnk4Ykl_sg

**Comment by rilian-la-te** [comment] 2023-04-06 08:10
@kambala-decapitator on develop golems are healed normally, but server complains. Complain will be fixed by PR #1883

**Comment by kambala-decapitator** [comment] 2023-04-06 08:25
> @kambala-decapitator on develop golems are healed normally, but server complains. Complain will be fixed by PR #1883

just to clarify, healing problem can be reproduced on all units (as you can see from the above video), not just golems

**Comment by rilian-la-te** [comment] 2023-04-06 08:55
@kambala-decapitator I tell you not about single app healing problem, but about this problem:

> can't reproduce the same on iOS, but there's a different issue: tried to heal Golem (where the cursor is), got this

This is also reproducible on all units? Anyway, can you try #1883 on single app?

**Comment by kambala-decapitator** [comment] 2023-04-06 11:25
@rilian-la-te well, in macOS + single app the same (strange log + no heal) happens on Imps (see the video). Since iOS is always Single App, I conclude that it's an issue with all units in Single App. Dunno why you think Golems are special.

can test the PR tomorrow.

**Comment by kambala-decapitator** [comment] 2023-04-08 09:42
> This is also reproducible on all units? Anyway, can you try #1883 on single app?

I see that one has already been merged. Just tried fresh beta + single app - same issue as before (tested Cure on Imps and Goblins).

**Closed** 2023-04-09 17:08 UTC
Labels: bug
