### ISSUE TITLE
Hero repeat bug

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2776] opened 2023-09-08 03:11 UTC
**Describe the bug**
It occurs in this video from youtube.
https://www.youtube.com/watch?v=soYs_tZ8uj8&t=10s
We can see hero did not get any artifacts from Dragon Utopia.
If he is a might hero with no spellbook, he even cannot use spell.

The probability should be very low, but it depends on the quantity of prisons in the map.

We can use a formula to show this probability:

P=1/y +1/(y-1) +1/(y-2) +... + 1/(y-x)

y refers to all quantity of hero, sometimes many town mods were installed, it will surpass 400.
x refers to the quantity of prison. Sometimes in a XL map, it should be 6-9. Expectation 7.2 from 15 XL random maps.

It will be very big if we use a G size map, with less town mods.

**Did it work earlier?**
It might exists for a long time. 

**Version**
 - OS: Windows
 - Version: 1.4.0

**Comment by nullkiller** [comment] 2023-10-29 20:20
So is it about duplicating heroes on map?

**Comment by IvanSavenko** [comment] 2023-10-29 20:22
Yeah, most likely. No way to confirm, but sounds very similar to other similar bugs

**Comment by IvanSavenko** [comment] 2023-11-19 21:02
Closing, duplicate of #2299

**Closed by IvanSavenko** 2023-11-19 21:02 UTC
Labels: bug
