### ISSUE TITLE
Crash on VisualLogger::updateWithLock

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#3816] opened 2024-04-21 17:44 UTC
**Describe the bug**
I create a 2 players hotseat game using a random XL 2 level map，2 vs 2. our players are blue and green. When game start , The window shows its the blue player's turn. Then I press enter key, but game crashed. 

**Game logs**
the log file was overwritten by a new game, but I keep the dmp file.
![1](https://github.com/vcmi/vcmi/assets/8289682/77a14e30-8963-4a80-9620-1cb612ad7e10)

I copied the symbol: VCMI_lib!ZN12VisualLogger14updateWithLockENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt8functionIFvR17IVisualLogBuilderEE+0x4ea5

It seems crashed on VisualLogger::updateWithLock
line 24: 	VisualLogBuilder builder(mapLines[channel]);

**To Reproduce**
I cant preproduce it, but I have seen the same stack in my friend's dmp file, he crashed in AI's turn.

**Expected behavior**
not crashed

**Actual behavior**
crashed

**Did it work earlier?**
no

**Screenshots**
no

**Version**
 - OS:  Windows
 - Version: daily build

**Additional context**
no

**Comment by DjWarmonger** [comment] 2024-04-21 18:20
Visual logger is a new NKAI feature. Should be disabled by default @nullkiller ?

**Comment by nullkiller** [comment] 2024-04-27 16:11
Should be disabled by default. It kind of works but no update should be called because NKAI_GRAPH_TRACE_LEVEL = 0 except if it was changed in custom build or was accidently enabled in some intermediate commit

**Comment by kdmcser** [comment] 2024-04-28 17:04
This is my custom build. No extra enviroment is set in this build. Should I force set NKAI_GRAPH_TRACE_LEVEL = 0 , and how to set?
This is my build command:
`conan install . --install-folder=./conan-generated   --no-imports   --build=never   --profile:build=default   --profile:host=CI/conan/mingw64-linux.jinja   -c tools.cmake.cmaketoolchain.presets:max_schema_version=2
cmake  -D CMAKE_BUILD_TYPE=Release --preset windows-mingw-conan-linux 
cmake --build -j8 --preset windows-mingw-conan-linux 
cmake --install  out/build/windows-mingw-conan-linux/ --prefix out/install/vcmi/`

**Comment by nullkiller** [comment] 2024-05-05 12:41
This is a constexpr variable, disabled by default and if you did not change source code it should not happen. Easy to test so. If writing **vslog graph** in console after first AI turn shows you nothing on UI and game still crashes - it is weird.

**Comment by kdmcser** [comment] 2024-05-06 13:09
Yes it crashed. After I type vslog graph and until all the ai move end, it crash with such stack. If I delete all code about logvisual, it is still crashed in other stack. So it is the memory visit problem?

**Comment by nullkiller** [comment] 2024-05-11 05:57
The collection of data for graph is controlled by AINodeStorage.h
constexpr int NKAI_GRAPH_TRACE_LEVEL = 1;

1 - graph is collected
0 - not collected

So if it is 0 I do not understand how it can crash. It should be 0 as any log collection hurts performance

**Comment by nullkiller** [comment] 2024-05-11 06:01
Sometimes when things happen which must not - clean and rebuild helps. I encountered such thing a few times with MSVC.

**Comment by nullkiller** [comment] 2024-05-23 18:34
Is it still crashing?

**Comment by nullkiller** [comment] 2024-05-29 05:56
Closing it for now as not reproducible.

**Closed by nullkiller** 2024-05-29 05:56 UTC
Labels: bug, nullkillerai, rmg
