### ISSUE TITLE
Moving/clicking items in the inventory

### ISSUE THREAD

**Issue by laser10111** [vcmi/vcmi#3094] opened 2023-10-22 12:09 UTC
**Describe the bug**
When interacting with items (trying to equip them) with eq, it automatically removes the hero from the inventory.

**Game logs**
[Autosave_1.zip](https://github.com/vcmi/vcmi/files/13063177/Autosave_1.zip)
**To Reproduce**
None

**Expected behavior**
Normal movement/equipment of artifact

**Actual behavior**
I can't move the artifact within the hero's inventory because it immediately kicks me out of the inventory and onto the map. reloading the save doesn't help.

**Did it work earlier?**
This is the first game session

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/46400607/50fd0530-3a85-4ad5-88b3-fcf586505b49)

**Version**
 - Windows 10
 - Version: 1.3.2

**Additional context**

**Comment by SoundSSGood** [comment] 2023-10-23 10:15
Duplicate heroes issue. Another Valeska is in prison at x=180, y=25.

**Comment by IvanSavenko** [comment] 2023-10-23 12:37
So probably duplicate of #2299

**Comment by nullkiller** [comment] 2023-10-29 08:18
Was it temp map?

**Comment by IvanSavenko** [comment] 2023-10-29 12:45
Extremely likely to be RMG map.

After quick look into code - is it possible for following to happen? I haven't noticed any code to prevent such scenario:
- player select hero X as starting hero
- RMG starts generating map
- RMG places hero X into prison and marks this hero as reserved
- Game is started and player receives second instance of hero X

Key part is that you must have non-random starting hero. For random selection there is indeed protection (via marking such heroes as reserved) but don't see anything that prevents placing starting hero into prison
@DjWarmonger what do you think?

**Comment by IvanSavenko** [comment] 2023-11-19 21:01
Closing, duplicate of #2299

**Closed by IvanSavenko** 2023-11-19 21:01 UTC
Labels: bug
