### ISSUE TITLE
Teleport issue

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#2677] opened 2023-08-26 14:25 UTC
**Describe the bug**
Game crashes when using teleport

**Game logs**
Server:
```
[2023-Aug-26 16:19:02.170294] TRACE network - 	Applied on gs: 9EndAction
[2023-Aug-26 16:19:02.170490] TRACE global - Activating red battle stack [3]: 2 of creatures.core.phoenix.name.plural from slot 2 of armyobj=605
[2023-Aug-26 16:19:02.170532] TRACE network - 	Sending to all clients: 20BattleSetActiveStack
[2023-Aug-26 16:19:02.170569] TRACE network - Sending a pack of type 20BattleSetActiveStack
[2023-Aug-26 16:19:02.170673] TRACE network - 	Applied on gs: 20BattleSetActiveStack
[2023-Aug-26 16:19:02.170709] TRACE global - Message 10MakeAction successfully applied!
[2023-Aug-26 16:19:02.170735] TRACE network - Sending a pack of type 14PackageApplied
[2023-Aug-26 16:19:15.143037] TRACE network - Received CPack of type 10MakeAction
[2023-Aug-26 16:19:15.143153] TRACE global - Making action: {BattleAction: side '0', stackNumber '4294967295', actionType '4', actionSubtype '63', target {2@{BattleHex: x '1', y '2', hex '35'},{BattleHex: x '15', y '6', hex '117'},}}
[2023-Aug-26 16:19:15.143174] TRACE network - 	Sending to all clients: 11StartAction
[2023-Aug-26 16:19:15.143187] TRACE network - Sending a pack of type 11StartAction
[2023-Aug-26 16:19:15.143446] TRACE network - 	Applied on gs: 11StartAction
[2023-Aug-26 16:19:15.143921] TRACE network - 	Sending to all clients: 16BattleLogMessage
[2023-Aug-26 16:19:15.143980] TRACE network - Sending a pack of type 16BattleLogMessage
[2023-Aug-26 16:19:15.144178] TRACE network - 	Applied on gs: 16BattleLogMessage
[2023-Aug-26 16:19:15.144231] TRACE network - 	Sending to all clients: 15BattleSpellCast
[2023-Aug-26 16:19:15.144256] TRACE network - Sending a pack of type 15BattleSpellCast
[2023-Aug-26 16:19:15.144336] TRACE network - 	Applied on gs: 15BattleSpellCast
[2023-Aug-26 16:19:15.144589] ERROR global - Disaster happened.
[2023-Aug-26 16:19:15.145296] ERROR global - Reason: 0xc0000005 - EXCEPTION_ACCESS_VIOLATION at 0033:0x7ff,8c3,873,711
[2023-Aug-26 16:19:15.145617] ERROR global - Attempt to read from 0x       0
[2023-Aug-26 16:19:15.146035] ERROR global - Thread ID: 9952
[2023-Aug-26 16:19:15.146908] ERROR global - Crash info will be put in VCMI_server.exe_crashinfo.dmp
```

**To Reproduce**
Teleport unit in town siege.

**Did it work earlier?**
idk

**Version**
 - OS: Windows 11
 - Version: latest nightly

**Screenshots**
[Peek 2023-08-26 16-19.webm](https://github.com/vcmi/vcmi/assets/13953785/45256247-75ac-4d28-81ac-8318d339fb5a)

**Comment by IvanSavenko** [comment] 2023-08-30 22:43
Unable to reproduce.
Tested as part of #2715 with similar scenario - teleport non-active stack inside walls during siege. No crash with expert water, teleport blocked with no water magic secondary skill.

**Comment by Laserlicht** [comment] 2023-08-30 23:03
I'm able to reproduce on multiple systems.

1. use save with nightly
2. attack town
3. teleport
![image](https://github.com/vcmi/vcmi/assets/13953785/907729d8-da2a-4649-be57-164062bd516b)


[test.vsgm1.zip](https://github.com/vcmi/vcmi/files/12480744/test.vsgm1.zip)

**Comment by IvanSavenko** [comment] 2023-08-31 12:37
Magic Elementals are immune to Teleport (or any other magic) so effect fails to apply - unit gets removed in `UnitEffect::transformTargetByRange` here:
```c++
	auto predicate = std::bind(&UnitEffect::eraseByImmunityFilter, this, m, _1);

	vstd::erase_if(targets, predicate);
```

Probably same issue will happen with Dragons.
@rilian-la-te Can you check this out? Not sure how to handle immunities for teleport - you're more familiar with this code.

**Comment by rilian-la-te** [comment] 2023-08-31 12:42
Maybe in weekend. In 1.3 all seems working.

@IvanSavenko can you write more details?
1. Who crashes? Server or Client?
2. GDB backtrace is available?
3. Did you bisected a crash? Can you do such bisect at least before your "battle split" PR?

**Comment by rilian-la-te** [comment] 2023-08-31 13:08
And why he can even select magic elementals for teleport? Is there an issue for sacrifice too?

**Comment by rilian-la-te** [comment] 2023-08-31 13:47
@IvanSavenko I understood why it crashes.

In this fragment:

```c++
	const auto *targetUnit = target[0].unitValue;
	const auto destination = target[1].hexValue;

	BattleStackMoved pack;
	pack.distance = 0;
	pack.stack = targetUnit->unitId();
```

last line is a line of the crash. Looks like target is removed from allowed, and then target[0].unitValue become NULL, so, we tried actually to get something from NULL.

But this should be filtered on "applicable" step. Maybe we messed up and applicable called before immunity kicks in?

**Comment by IvanSavenko** [comment] 2023-08-31 13:52
I reproduced this on 1.3.0 build, way before my battle changes. And no - don't remember removing any such checks.

**Comment by rilian-la-te** [comment] 2023-08-31 13:53
@IvanSavenko will try. Is this reproductible with fresh start?

**Comment by IvanSavenko** [comment] 2023-08-31 13:55
Yep.
Tested on day 1 by attacking town with Magic Elementals in my army and attempting to teleport them

**Comment by rilian-la-te** [comment] 2023-08-31 14:04
@IvanSavenko looks like applicable is not checked correctly for this spell.

**Comment by rilian-la-te** [comment] 2023-09-01 20:53
@IvanSavenko please, close this, I do not have rights.

**Comment by IvanSavenko** [comment] 2023-09-01 20:56
Ah, forgot that Github won't close stuff merged in beta...

**Closed by IvanSavenko** 2023-09-01 20:56 UTC
Labels: bug

**Comment by Povelitelh3** [comment] 2023-10-15 19:32
I have crash in latest develop (1.4.0.3906217ef5ddb11e083d772fe292a5c9ec98bae7, mingw Ubuntu)

```
[2023-Oct-15 22:30:44.679356] TRACE global - CBattleConsole message: Галтран направляет "Телепортация" на Скелеты.
[2023-Oct-15 22:30:44.679900] TRACE network - 	Made second apply on cl: 16BattleLogMessage
[2023-Oct-15 22:30:44.680294] TRACE network - Received CPack of type 15BattleSpellCast
[2023-Oct-15 22:30:44.680565] TRACE network - 	Made first apply on cl: 15BattleSpellCast
[2023-Oct-15 22:30:44.680986] TRACE network - 	Applied on gs: 15BattleSpellCast
[2023-Oct-15 22:30:44.681479] TRACE network - 	Made second apply on cl: 15BattleSpellCast
[2023-Oct-15 22:30:44.681871] TRACE network - Received CPack of type 16BattleStackMoved
[2023-Oct-15 22:30:44.683477] ERROR global - Disaster happened.
```
[AAA.zip](https://github.com/vcmi/vcmi/files/12910498/AAA.zip)
