### ISSUE TITLE
SantaGremlin summons invisible gremlin guards

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2736] opened 2023-09-02 12:37 UTC
**Describe the bug**
Santa gremlins should summon gremlin guards at start of battle. Seems that they are there, AI attacks them... but they are invisible to the user.

Cannot tell if mod issue or VCMI

![image](https://github.com/vcmi/vcmi/assets/15194321/80eb8386-a238-4167-859e-ae3318ede211)

**To Reproduce**
1. Use WoG mod
2. Start a battle with santa gremlin
3. see error
4. 
 - OS: [e.g. Windows, 
 - Version: [VCMI develop

**Comment by misiokles** [comment] 2023-09-02 12:48
Duplicate of:
https://github.com/vcmi/vcmi/issues/2644
https://github.com/vcmi/vcmi/issues/2521
https://github.com/vcmi/vcmi/issues/2477

**Comment by krs0** [comment] 2023-09-02 13:05
So it bothers enough a lot of people :)

**Comment by by003** [comment] 2023-09-03 01:48
Same as courtyard mod user

**Comment by IvanSavenko** [comment] 2023-09-06 08:20
Closing as duplicate of #2477

**Closed by IvanSavenko** 2023-09-06 08:20 UTC
Labels: bug, duplicate, modding
