### ISSUE TITLE
Error while generating random map

### ISSUE THREAD

**Issue by unluckychild** [vcmi/vcmi#2819] opened 2023-09-13 10:16 UTC
I usually play 1vs7 on big maps in HOTA, but here, it shows no possible map template. In random map template selection, is there a template, which creates a random map for ANY map size and number of players?

I tried other expansions (when i try one, i disable rest), but same result

**Comment by IvanSavenko** [comment] 2023-09-13 11:12
Hi. What random map settings are you using?
Keep in mind that "Computer players" option is bugged at the moment. Please use only "Human or Computer players" option.
So if you want to generate map for 1 human and 7 AI's simply select 8 "Human or Computer players" and keep "Computer players" at 0

**Comment by unluckychild** [comment] 2023-09-13 11:35
Thank you, that solved it.

**Comment by IvanSavenko** [comment] 2023-09-13 11:43
- Duplicate of #2596

**Comment by unluckychild** [comment] 2023-09-13 12:08
One last Question:

How much is the game slowed down if i enable ~10 new towns. Aprox...

**Comment by IvanSavenko** [comment] 2023-09-13 12:12
Not much. This will use a bit more memory, but should have minimal effect on actual performance.

**Comment by unluckychild** [comment] 2023-09-13 12:21
I read on reddit, that on bigger maps enabling more towns makes the game much slower. 
Normally = 9 maps, adding another 9 maps is like almost twice slower

**Comment by IvanSavenko** [comment] 2023-09-13 12:24
Yes, larger map sizes are definitely slower, especially for AI turns. 
So I won't recommend playing anything over XL on low-end systems, e.g. Android.

However mods (including new towns) should generally have no noticeable effect on performance

**Comment by unluckychild** [comment] 2023-09-13 13:36
Now really last question: Did VCMI fix slow AI turns, when dimensional door and fly is enabled?

**Comment by IvanSavenko** [comment] 2023-09-13 13:42
Don't know. I think our AI can't use Dimension Door, but not sure about Fly.

**Comment by unluckychild** [comment] 2023-09-14 01:37
Its pity that VCMI didnt fix that, i really wanted to try new towns and other mods, but maps generation and even starting AI turns are very slow compared to HD launcher's HOTA. 

FOr example, a normal random XL map 1v7 in first turn, VCMI AI turn is ~10sec, in HOTA like 2 secs. I thought that was because of settings, so i tried all other combinations and various settings, but result was still same. I even disabled all and activated only VCMI's HOTA but it is much slower than HD launcher's HOTA.

**Closed** 2024-01-15 21:43 UTC
